# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/utils/
#   IMPORT INSTEAD:      from kailash_mcp.utils import ...
#
# This is the package-level shim for `kailash.mcp_server.utils`. The
# submodules (cache, config, formatters, metrics) each have their own
# shim files in this directory.
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │   STOP. Do NOT edit this file.                                   │
# │   Canonical:                                                     │
# │     packages/kailash-mcp/src/kailash_mcp/utils/__init__.py       │
# │   Edits to this shim will be LOST.                               │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.utils import CacheManager, ConfigManager, ...
#
# Tracking: src/kailash/mcp_server/DEPRECATED.md, SPEC-01
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM package -- canonical at :mod:`kailash_mcp.utils`."""

from __future__ import annotations

import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.utils is deprecated; use `kailash_mcp.utils`. "
    "See src/kailash/mcp_server/DEPRECATED.md.",
    DeprecationWarning,
    stacklevel=2,
)

from kailash_mcp.utils import *  # noqa: F401,F403,E402


def __getattr__(name: str):
    import kailash_mcp.utils as _canonical

    if hasattr(_canonical, name):
        _warnings.warn(
            f"Accessing kailash.mcp_server.utils.{name} is deprecated; "
            f"use kailash_mcp.utils.{name} instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return getattr(_canonical, name)
    raise AttributeError(f"module 'kailash.mcp_server.utils' has no attribute {name!r}")
