# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/utils/config.py
#   IMPORT INSTEAD:      from kailash_mcp.utils.config import ...
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │   STOP. Do NOT edit this file.                                   │
# │   Canonical: packages/kailash-mcp/src/kailash_mcp/utils/config.py│
# │   Edits to this shim will be LOST.                               │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.utils.config import ConfigManager, ...
#
# Implementation: sys.modules identity swap for mock.patch compatibility.
# Tracking: src/kailash/mcp_server/DEPRECATED.md, SPEC-01
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM -- canonical at :mod:`kailash_mcp.utils.config`."""

from __future__ import annotations

import sys as _sys
import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.utils.config is deprecated; use "
    "`kailash_mcp.utils.config`. See "
    "src/kailash/mcp_server/DEPRECATED.md.",
    DeprecationWarning,
    stacklevel=2,
)

import kailash_mcp.utils.config as _canonical  # noqa: E402

_sys.modules[__name__] = _canonical
