# Copyright 2026 Terrene Foundation
# SPDX-License-Identifier: Apache-2.0

"""TrustPlane — EATP-powered trust environment for human-AI collaborative work."""

__version__ = "0.2.1"

from trustplane.models import (
    CommunicationConstraints,
    ConstraintEnvelope,
    DataAccessConstraints,
    DecisionRecord,
    DecisionType,
    EscalationRecord,
    ExecutionRecord,
    FinancialConstraints,
    HumanCompetency,
    InterventionRecord,
    MilestoneRecord,
    OperationalConstraints,
    ProjectManifest,
    ReviewRequirement,
    TemporalConstraints,
    VerificationCategory,
)
from trustplane.exceptions import (
    ArchiveError,
    BudgetExhaustedError,
    ConstraintViolationError,
    IdentityError,
    JWKSError,
    KeyExpiredError,
    KeyManagerError,
    KeyNotFoundError,
    LockTimeoutError,
    RBACError,
    RecordNotFoundError,
    SchemaMigrationError,
    SchemaTooNewError,
    SigningError,
    StoreConnectionError,
    StoreQueryError,
    StoreTransactionError,
    TLSSyslogError,
    TokenVerificationError,
    TrustDecryptionError,
    TrustPlaneError,
    TrustPlaneStoreError,
    VerificationError,
)
from trustplane.project import TrustProject
from trustplane.store import TrustPlaneStore
from trustplane.store.filesystem import FileSystemTrustPlaneStore
from trustplane.store.sqlite import SqliteTrustPlaneStore

__all__ = [
    "TrustProject",
    "TrustPlaneStore",
    "FileSystemTrustPlaneStore",
    "SqliteTrustPlaneStore",
    "TrustPlaneError",
    "TrustPlaneStoreError",
    "TrustDecryptionError",
    "RecordNotFoundError",
    "SchemaTooNewError",
    "SchemaMigrationError",
    "ConstraintViolationError",
    "BudgetExhaustedError",
    "IdentityError",
    "TokenVerificationError",
    "JWKSError",
    "KeyManagerError",
    "KeyNotFoundError",
    "KeyExpiredError",
    "SigningError",
    "VerificationError",
    "StoreConnectionError",
    "StoreQueryError",
    "StoreTransactionError",
    "RBACError",
    "ArchiveError",
    "TLSSyslogError",
    "LockTimeoutError",
    "CommunicationConstraints",
    "ConstraintEnvelope",
    "DataAccessConstraints",
    "DecisionRecord",
    "DecisionType",
    "EscalationRecord",
    "ExecutionRecord",
    "FinancialConstraints",
    "HumanCompetency",
    "InterventionRecord",
    "MilestoneRecord",
    "OperationalConstraints",
    "ProjectManifest",
    "ReviewRequirement",
    "TemporalConstraints",
    "VerificationCategory",
]
