"""Tier-2a integration coverage for ``kaizen.nodes.rag.multimodal``.

F8 shard B4. The 3 multimodal RAG nodes' real backend is the ``[rag]`` extra's
own ``Pillow`` and ``numpy`` — no container, no LLM key. These tests generate a
REAL small PNG with ``PIL.Image.new(...)`` in a fixture and feed real image
bytes / real file paths to the nodes; ``numpy`` backs the embedding-fallback
math. NO mocking (``@patch`` / ``MagicMock`` / ``unittest.mock`` are BLOCKED in
Tier 2 per the 3-tier testing rule). The dep IS the infra.

``MultimodalRAGNode`` is a ``WorkflowNode``; its ``_create_workflow()`` builds
a sub-workflow whose ``PythonCodeNode`` ``code=`` templates carry retrieval
logic. End-to-end runtime execution of that graph needs an LLM key (the
``query_analyzer`` / ``response_generator`` are ``LLMAgentNode`` steps) — a
documented scope boundary. This file covers what is exercisable with the
``[rag]`` extra alone: the codegen templates exercised DIRECTLY via ``exec``
against malformed input (the B1 codegen-regression pattern), plus the graph
shape and node parameter contracts.

Assertions are structural: result keys, score ranges/ordering, list lengths,
typed-error raises, real-PNG byte properties.
"""

from __future__ import annotations

import io

import numpy as np
import pytest
from PIL import Image

from kaizen.nodes.rag.multimodal import (
    ImageTextMatchingNode,
    MultimodalRAGNode,
    VisualQuestionAnsweringNode,
)

pytestmark = pytest.mark.integration


# ==========================================================================
# Real-Pillow fixtures — the [rag] extra's Pillow IS the infrastructure.
# ==========================================================================


@pytest.fixture
def architecture_png(tmp_path):
    """A real 32x32 RGB PNG written to a tmp path named 'architecture_*'.

    The name carries the 'architecture' sentinel the multimodal_encoder
    codegen branches on; the bytes are a genuine Pillow-encoded PNG.
    """
    path = tmp_path / "architecture_diagram.png"
    img = Image.new("RGB", (32, 32), color=(40, 90, 180))
    img.save(path, format="PNG")
    return path


@pytest.fixture
def diagram_png_bytes():
    """Real PNG bytes (no file) for nodes / collections that take raw bytes."""
    buf = io.BytesIO()
    Image.new("RGB", (16, 16), color=(200, 200, 200)).save(buf, format="PNG")
    return buf.getvalue()


# ==========================================================================
# Real-image-path behavior — VQA + ITM against a genuine Pillow PNG
# ==========================================================================


class TestMultimodalNodesAgainstRealImages:
    """The nodes accept real image paths / bytes generated by Pillow."""

    def test_real_png_is_valid_decodable_image(self, architecture_png):
        """Sanity: the fixture writes a real, Pillow-decodable PNG."""
        with Image.open(architecture_png) as reopened:
            assert reopened.format == "PNG"
            assert reopened.size == (32, 32)

    def test_vqa_run_against_real_png_path(self, architecture_png):
        """VQA.run() accepts a real on-disk PNG path and returns the contract."""
        node = VisualQuestionAnsweringNode()
        result = node.run(
            image_path=str(architecture_png),
            question="What components are shown in this diagram?",
        )
        assert set(result.keys()) == {
            "answer",
            "confidence",
            "image_caption",
            "detected_objects",
            "model_used",
        }
        assert len(result["detected_objects"]) == 4

    def test_image_text_matching_against_real_png_collection(
        self, architecture_png, diagram_png_bytes
    ):
        """ITM.run() ranks a collection whose items reference real PNG data."""
        node = ImageTextMatchingNode()
        collection = [
            {
                "caption": "architecture diagram",
                "tags": ["diagram"],
                "path": str(architecture_png),
            },
            {
                "caption": "grey placeholder",
                "tags": ["photo"],
                "bytes": diagram_png_bytes,
            },
        ]
        result = node.run(query="architecture diagram", collection=collection, top_k=2)
        scores = result["similarity_scores"]
        assert scores == sorted(scores, reverse=True)
        assert scores[0] == 0.9
        assert result["total_searched"] == 2


# ==========================================================================
# MultimodalRAGNode codegen templates — exercised directly via exec.
#
# The _create_workflow() PythonCodeNode code= templates carry retrieval logic
# that the run()-path nodes do not — per the B1/B2/B3 two-path lesson, the
# codegen templates are behaviorally covered by exec-ing the rendered function
# against malformed input. This is the B1 codegen-regression pattern.
# ==========================================================================


def _node_code(workflow, node_id):
    """Extract the rendered ``code=`` string of a codegen PythonCodeNode."""
    node = workflow.nodes[node_id]
    config = node.config if hasattr(node, "config") else {}
    return config["code"]


def _exec_codegen_fn(workflow, node_id, fn_name):
    """exec a codegen PythonCodeNode's rendered code and return its function.

    The MultimodalRAGNode codegen functions (``preprocess_documents``,
    ``encode_multimodal``, ``retrieve_multimodal``) build a local ``result``
    dict as their FINAL statement but never ``return`` it — the function's
    output is unreachable to a direct caller (a separate WorkflowNode codegen
    finding, reported in the shard summary). To exercise the function's logic
    behaviorally, this helper appends ``\\n    return result`` so the final
    ``result`` local is returned. The appended line continues the function
    body at the same 4-space indent as the ``result = {`` block.
    """
    code = _node_code(workflow, node_id)
    namespace: dict = {"np": np}
    exec(code + "\n    return result\n", namespace)
    return namespace[fn_name]


class TestMultimodalRAGCodegenTemplates:
    """Behavioral coverage of the MultimodalRAGNode codegen templates by
    exec-ing the rendered functions against well-formed and malformed input.
    No mocking — real Python execution of the real shipped template text."""

    def test_doc_preprocessor_separates_text_and_image_documents(self):
        """The doc_preprocessor template splits a mixed-media corpus into
        text_docs and image_docs."""
        fn = _exec_codegen_fn(
            MultimodalRAGNode()._create_workflow(),  # type: ignore[attr-defined]
            "doc_preprocessor",
            "preprocess_documents",
        )
        result = fn(
            [
                {"type": "text", "content": "transformers explained", "id": "t1"},
                {"type": "image", "image_path": "diagram.png", "caption": "a diagram"},
            ]
        )
        block = result["preprocessed_docs"]
        assert len(block["text_documents"]) == 1
        assert len(block["image_documents"]) == 1
        assert block["text_documents"][0]["content"] == "transformers explained"

    def test_doc_preprocessor_skips_non_dict_document_element(self):
        """A non-dict document element is skipped, not crashed on.

        Documents are arbitrary user input; a bare string has no `.get`.
        Pre-fix this raised AttributeError ('str' object has no attribute
        'get') — see tests/regression/test_issue_f8b4_multimodal_defects.py.
        """
        fn = _exec_codegen_fn(
            MultimodalRAGNode()._create_workflow(),  # type: ignore[attr-defined]
            "doc_preprocessor",
            "preprocess_documents",
        )
        result = fn(
            ["not-a-dict", {"type": "text", "content": "real doc", "id": "t1"}, 42]
        )
        text_docs = result["preprocessed_docs"]["text_documents"]
        assert len(text_docs) == 1
        assert text_docs[0]["content"] == "real doc"

    def test_doc_preprocessor_handles_present_but_none_content(self):
        """A document with content=None does not crash the preprocessor."""
        fn = _exec_codegen_fn(
            MultimodalRAGNode()._create_workflow(),  # type: ignore[attr-defined]
            "doc_preprocessor",
            "preprocess_documents",
        )
        result = fn([{"type": "text", "content": None, "id": "t1"}])
        assert result["preprocessed_docs"]["text_documents"][0]["content"] == ""

    def test_multimodal_encoder_encodes_text_and_image_documents(self):
        """The multimodal_encoder template produces embeddings for both
        modalities against real numpy-backed math."""
        fn = _exec_codegen_fn(
            MultimodalRAGNode()._create_workflow(),  # type: ignore[attr-defined]
            "multimodal_encoder",
            "encode_multimodal",
        )
        encoded = fn(
            text_docs=[{"id": "t1", "content": "neural net", "title": "ml"}],
            image_docs=[{"id": "i1", "path": "architecture.png", "caption": "arch"}],
            query="neural net architecture",
            modality_analysis={},
        )
        block = encoded["encoded_data"]
        assert len(block["text_embeddings"]) == 1
        assert len(block["image_embeddings"]) == 1
        assert len(block["query_embedding"]) > 0

    def test_multimodal_encoder_handles_present_but_none_content(self):
        """A text doc with content=None / title=None does not crash the `+`
        concatenation in the encoder.

        Pre-fix this raised TypeError (unsupported operand type(s) for +:
        'NoneType' and 'str').
        """
        fn = _exec_codegen_fn(
            MultimodalRAGNode()._create_workflow(),  # type: ignore[attr-defined]
            "multimodal_encoder",
            "encode_multimodal",
        )
        encoded = fn(
            text_docs=[{"id": "t1", "content": None, "title": None}],
            image_docs=[],
            query="some query",
            modality_analysis={},
        )
        assert len(encoded["encoded_data"]["text_embeddings"]) == 1

    def test_multimodal_encoder_handles_none_image_path(self):
        """An image doc with path=None does not crash image_encoder.lower().

        Pre-fix this raised AttributeError ('NoneType' object has no
        attribute 'lower').
        """
        fn = _exec_codegen_fn(
            MultimodalRAGNode()._create_workflow(),  # type: ignore[attr-defined]
            "multimodal_encoder",
            "encode_multimodal",
        )
        encoded = fn(
            text_docs=[],
            image_docs=[{"id": "i1", "path": None, "caption": "a caption"}],
            query="some query",
            modality_analysis={},
        )
        assert len(encoded["encoded_data"]["image_embeddings"]) == 1

    def test_cross_modal_retriever_ranks_and_separates_by_modality(self):
        """The cross_modal_retriever template scores, sorts, and splits
        results by text/image modality."""
        workflow = MultimodalRAGNode()._create_workflow()  # type: ignore[attr-defined]
        # cross_modal_retriever reads a free `query` variable (a workflow
        # input); inject it into the exec namespace before defining the fn.
        code = _node_code(workflow, "cross_modal_retriever")
        namespace: dict = {"np": np, "query": "show me the architecture diagram"}
        exec(code + "\n    return result\n", namespace)
        encoded_data = {
            "query_embedding": [0.5] * 10,
            "text_embeddings": [
                {"id": "t1", "embedding": [0.5] * 10, "content": "text preview"}
            ],
            "image_embeddings": [
                {"id": "i1", "embedding": [0.5] * 10, "path": "p.png", "caption": "c"}
            ],
        }
        result = namespace["retrieve_multimodal"](encoded_data, {})
        block = result["retrieval_results"]
        assert len(block["text_results"]) == 1
        assert len(block["image_results"]) == 1
        assert block["modality_distribution"]["text_count"] == 1

    def test_cross_modal_retriever_handles_none_query_input(self):
        """A None query workflow-input does not crash the retriever's
        `.lower()` visual-term boost.

        Pre-fix this raised AttributeError ('NoneType' object has no
        attribute 'lower').
        """
        workflow = MultimodalRAGNode()._create_workflow()  # type: ignore[attr-defined]
        code = _node_code(workflow, "cross_modal_retriever")
        namespace: dict = {"np": np, "query": None}
        exec(code + "\n    return result\n", namespace)
        encoded_data = {
            "query_embedding": [0.5] * 10,
            "text_embeddings": [],
            "image_embeddings": [
                {"id": "i1", "embedding": [0.5] * 10, "path": "p.png", "caption": "c"}
            ],
        }
        result = namespace["retrieve_multimodal"](encoded_data, {})
        assert len(result["retrieval_results"]["image_results"]) == 1


# ==========================================================================
# MultimodalRAGNode — graph shape + parameter contract
# ==========================================================================


class TestMultimodalRAGNodeGraphShape:
    """The wrapped sub-workflow's structural contract — node count, the
    parameter surface, and serialisation."""

    def test_create_workflow_wires_six_nodes(self):
        """The multimodal RAG sub-workflow wires exactly six nodes."""
        node = MultimodalRAGNode()
        workflow = node._create_workflow()  # type: ignore[attr-defined]
        assert len(workflow.nodes) == 6

    def test_enable_ocr_flag_threads_into_doc_preprocessor_codegen(self):
        """The enable_ocr constructor flag is interpolated into the
        doc_preprocessor codegen template (True vs False render distinctly)."""
        ocr_on = MultimodalRAGNode(enable_ocr=True)
        ocr_off = MultimodalRAGNode(enable_ocr=False)
        code_on = _node_code(
            ocr_on._create_workflow(), "doc_preprocessor"  # type: ignore[attr-defined]
        )
        code_off = _node_code(
            ocr_off._create_workflow(), "doc_preprocessor"  # type: ignore[attr-defined]
        )
        assert "if True and image_path" in code_on
        assert "if False and image_path" in code_off

    def test_image_encoder_flag_threads_into_encoder_codegen(self):
        """The image_encoder constructor value reaches the encoder template."""
        node = MultimodalRAGNode(image_encoder="blip-large")
        code = _node_code(
            node._create_workflow(), "multimodal_encoder"  # type: ignore[attr-defined]
        )
        assert "blip-large" in code

    def test_get_parameters_exposes_input_surface(self):
        """get_parameters returns the wrapped sub-workflow's input mapping."""
        params = MultimodalRAGNode().get_parameters()
        assert len(params) > 0

    def test_to_dict_round_trips_node_type(self):
        """to_dict serialises the node with its registered type name."""
        data = MultimodalRAGNode().to_dict()
        assert data["type"] == "MultimodalRAGNode"
