# Copyright 2026 Terrene Foundation
# SPDX-License-Identifier: Apache-2.0
"""Regression test for issue #774 — bulk_create AttributeError on bare-type field specs.

Before the fix, ``self.model_fields.get(field_name, {}).get("type")`` at
``dataflow/core/nodes.py:837`` raised
``AttributeError: type object 'str' has no attribute 'get'`` when callers
passed bare-type field-spec form (``{"name": str}``) to
``NodeGenerator.generate_bulk_nodes``. Canonical ``@db.model`` produces
dict-form (``{"name": {"type": str, "required": True}}``); the public
``NodeGenerator`` API accepted both shapes by signature but only the
dict-form by behavior.

Fix: ``_normalize_field_specs`` at the constructor boundary
(``DataFlowNode.__init__``) normalizes any caller-supplied shape to
canonical dict-form, and the module-level helpers (``_coerce_record_id``,
``convert_datetime_fields``) defensively accept both shapes for any
external caller bypassing the node constructor.

Test layers:

1. **Tier 1 (unit)** — replays the original failing test
   (``test_bulk_create_with_data_parameter``) via
   ``NodeGenerator.generate_bulk_nodes`` with bare-type fields and asserts
   ``validate_inputs`` no longer raises ``AttributeError``.
2. **Tier 1 (structural)** — pins the ``_normalize_field_specs`` contract
   so future refactors that change the normalization shape break loudly.
3. **Tier 2 (integration)** — exercises ``db.express.bulk_create`` against
   real PostgreSQL with a ``@db.model``-decorated class (dict-form path)
   to prove the canonical happy path is unaffected.

Per ``rules/testing.md`` § "Behavioral Regression Tests Over Source-Grep"
and § "End-to-End Pipeline Regression": the tests CALL the function and
assert the user-visible outcome, not the source-line state.
"""

from __future__ import annotations

import time
import uuid
from unittest.mock import MagicMock

import pytest

from dataflow.core.nodes import NodeGenerator, _normalize_field_specs

pytestmark = pytest.mark.regression


# ---------------------------------------------------------------------------
# Tier 1: Unit — bare-type field-spec form does not crash validate_inputs
# ---------------------------------------------------------------------------


def _build_bulk_node_with_bare_type_fields():
    """Build a BulkCreate node via the public NodeGenerator API with bare-type fields.

    Mirrors the failing test
    ``tests/unit/core/test_auto_generated_bulk_parameter_mapping.py``
    ``TestAutoGeneratedBulkParameterMapping::setup_method`` shape.
    """
    mock_dataflow = MagicMock()
    mock_dataflow.config.security.multi_tenant = False
    mock_dataflow._tenant_context = {}
    generator = NodeGenerator(mock_dataflow)

    # Bare-type form — the shape that crashed pre-fix.
    test_fields = {"name": str, "email": str, "active": bool}
    nodes = generator.generate_bulk_nodes("User", test_fields)
    return nodes["UserBulkCreateNode"]


def test_bulk_create_validate_inputs_does_not_crash_on_bare_type_fields():
    """Pre-fix: AttributeError: type object 'str' has no attribute 'get'.

    Post-fix: validate_inputs returns successfully because the constructor
    normalizes bare-type values into canonical dict-form.
    """
    bulk_create_node = _build_bulk_node_with_bare_type_fields()
    instance = bulk_create_node()

    test_data = [
        {"name": "Alice", "email": "alice@example.com"},
        {"name": "Bob", "email": "bob@example.com"},
    ]

    # The crash site: validate_inputs walks model_fields to enforce the
    # declared-string guard against dict / list / set / tuple values.
    # On bare-type input, the .get(name, {}).get("type") chain raised
    # AttributeError ('str' has no attribute 'get').
    validated = instance.validate_inputs(data=test_data)
    assert isinstance(
        validated, dict
    ), "validate_inputs must return a dict after normalization"


def test_bulk_create_run_returns_dict_with_bare_type_fields():
    """End-to-end mirror of the originally failing test (``data=`` kwarg).

    This test exercises ``.run(data=...)`` against the mock-DataFlow shape
    used by ``tests/unit/core/test_auto_generated_bulk_parameter_mapping.py``.
    The original test only asserted ``isinstance(result, dict)``; this
    regression test pins the same outcome for the bare-type field-spec
    branch so the bug class cannot recur silently.
    """
    bulk_create_node = _build_bulk_node_with_bare_type_fields()
    instance = bulk_create_node()

    test_data = [
        {"name": "Alice", "email": "alice@example.com"},
        {"name": "Bob", "email": "bob@example.com"},
    ]
    result = instance.run(data=test_data)
    assert isinstance(result, dict)


def test_normalize_field_specs_accepts_both_shapes():
    """Structural invariant: the normalizer accepts dict-form AND bare-type.

    If a future refactor changes the canonical shape, this test fails
    loudly and forces a re-audit of every model_fields call site.
    """
    # Bare-type input → dict-form output
    bare = {"name": str, "active": bool}
    out = _normalize_field_specs(bare)
    assert out == {
        "name": {"type": str, "required": True},
        "active": {"type": bool, "required": True},
    }

    # Already dict-form → preserved unchanged
    dict_form = {"id": {"type": int, "required": True, "primary_key": True}}
    assert _normalize_field_specs(dict_form) == dict_form

    # Mixed shape (defense-in-depth)
    mixed = {"id": {"type": int, "primary_key": True}, "name": str}
    assert _normalize_field_specs(mixed) == {
        "id": {"type": int, "primary_key": True},
        "name": {"type": str, "required": True},
    }

    # Empty / None safe
    assert _normalize_field_specs({}) == {}
    assert _normalize_field_specs(None) == {}  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# Tier 2: Integration — real PostgreSQL via @db.model canonical happy path
# ---------------------------------------------------------------------------


@pytest.fixture
async def pg_test_suite():
    """IntegrationTestSuite for real-Postgres regression coverage.

    Skips when shared Docker Postgres on port 5434 is unreachable —
    matches the convention from test_issue_711_transactions_sync.py
    and the broader regression suite.
    """
    from tests.infrastructure.test_harness import IntegrationTestSuite

    suite = IntegrationTestSuite()
    try:
        async with suite.session():
            yield suite
    except Exception as exc:
        pytest.skip(
            f"Cannot reach PostgreSQL test infra: {type(exc).__name__}: {exc}. "
            f"Ensure shared SDK Docker is running on port 5434."
        )


@pytest.mark.integration
async def test_bulk_create_round_trip_via_db_model_dict_form(pg_test_suite):
    """Canonical ``@db.model`` path produces dict-form fields and round-trips.

    Asserts the fix preserves the canonical happy path: ``@db.model``
    populates ``_model_fields`` in dict-form (engine.py:1858), the
    constructor normalizer is a no-op, and ``db.express.bulk_create``
    completes without error.

    Per ``rules/testing.md`` § "State Persistence Verification": every
    write is verified with a read-back.
    """
    from dataflow import DataFlow

    db_url = pg_test_suite.config.url
    table_suffix = f"{int(time.time() * 1_000_000)}_{uuid.uuid4().hex[:6]}"
    db = DataFlow(db_url, auto_migrate=True)

    @db.model
    class Issue774User:  # noqa: N801 — table name must include timestamp for isolation
        name: str
        email: str
        active: bool

    # Force unique table name to isolate between parallel test runs.
    Issue774User.__tablename__ = f"issue774_users_{table_suffix}"  # type: ignore[attr-defined]

    await db.initialize()
    try:
        records = [
            {
                "name": "Alice",
                "email": f"alice_{table_suffix}@example.com",
                "active": True,
            },
            {
                "name": "Bob",
                "email": f"bob_{table_suffix}@example.com",
                "active": False,
            },
        ]
        # The path that crashed pre-fix on bare-type input now flows
        # through the canonical dict-form path. Asserts the contract is
        # whole: validate → execute → result.
        result = await db.express.bulk_create("Issue774User", records)
        assert isinstance(result, (list, dict))

        # Read-back proves persistence (rules/testing.md §
        # "State Persistence Verification").
        rows = await db.express.list("Issue774User", filter={})
        assert len(rows) >= 2
        emails = {row["email"] for row in rows}
        assert f"alice_{table_suffix}@example.com" in emails
        assert f"bob_{table_suffix}@example.com" in emails
    finally:
        # Best-effort cleanup; teardown errors do NOT mask test failures.
        try:
            async with pg_test_suite.get_connection() as conn:
                await conn.execute(
                    f'DROP TABLE IF EXISTS "issue774_users_{table_suffix}" CASCADE'
                )
        except Exception:  # noqa: BLE001 — cleanup-path
            pass
