# Copyright 2026 Terrene Foundation
# SPDX-License-Identifier: Apache-2.0

"""Tier 2 integration tests for the public ``kailash.EventBus`` primitive.

Real in-memory backend, real workflow execution — NO mocking (per the
3-tier testing rule).  Covers issue #1054 acceptance criteria:

* ``from kailash import EventBus`` works AND ``dir(kailash)`` exposes it.
* publish-then-subscribe round-trip through the in-memory backend
  asserts handler invocation with the ORIGINAL payload + correlation_id.
* backend selectable via env var with identical primitive shape.
* WorkflowBuilder step publishes via the bus (real workflow run).
* Redis Streams broker backend (xfail without a live Redis).
"""

from __future__ import annotations

import asyncio
import os

import pytest

import kailash
from kailash import DomainEvent, EventBus, Subscription
from kailash.events import (
    EventBackend,
    InMemoryEventBackend,
    RedisStreamsEventBackend,
    create_backend,
)

pytestmark = pytest.mark.integration


# ---------------------------------------------------------------------------
# Acceptance: public surface
# ---------------------------------------------------------------------------


def test_eventbus_is_public_surface():
    """from kailash import EventBus works AND dir(kailash) exposes it."""
    assert hasattr(kailash, "EventBus")
    assert hasattr(kailash, "Subscription")
    assert hasattr(kailash, "DomainEvent")
    assert "EventBus" in dir(kailash)
    assert "EventBus" in kailash.__all__
    assert "Subscription" in kailash.__all__
    assert "DomainEvent" in kailash.__all__


def test_eventbus_required_surface_shape():
    """The minimum surface from issue #1054 exists with the right shape."""
    import inspect

    pub = inspect.signature(EventBus.publish)
    assert "event_type" in pub.parameters
    assert "payload" in pub.parameters
    assert "correlation_id" in pub.parameters
    assert pub.parameters["correlation_id"].kind == inspect.Parameter.KEYWORD_ONLY
    assert inspect.iscoroutinefunction(EventBus.publish)

    sub = inspect.signature(EventBus.subscribe)
    assert "event_type" in sub.parameters
    assert "handler" in sub.parameters
    assert not inspect.iscoroutinefunction(EventBus.subscribe)

    assert inspect.iscoroutinefunction(Subscription.unsubscribe)


# ---------------------------------------------------------------------------
# Acceptance: in-memory round-trip with ORIGINAL payload + correlation_id
# ---------------------------------------------------------------------------


async def test_publish_subscribe_roundtrip_original_payload():
    """Tier 2: publish -> subscribe round-trip asserts the handler is
    invoked with the ORIGINAL payload object content."""
    bus = EventBus()  # default in-memory, no external dependency
    assert bus.backend_name == "InMemoryEventBackend"

    received: list[dict] = []

    async def handler(payload):
        received.append(payload)

    sub = bus.subscribe("order.created", handler)
    assert isinstance(sub, Subscription)
    assert sub.active is True

    original = {"order_id": "o-99", "total": 42.5, "items": ["a", "b"]}
    await bus.publish("order.created", original)
    await asyncio.sleep(0.02)

    assert len(received) == 1
    assert received[0] == original
    assert received[0]["items"] == ["a", "b"]

    await sub.unsubscribe()
    assert sub.active is False
    # unsubscribe is idempotent
    await sub.unsubscribe()

    await bus.publish("order.created", {"order_id": "o-100"})
    await asyncio.sleep(0.02)
    assert len(received) == 1  # unchanged after unsubscribe

    await bus.close()


async def test_correlation_id_roundtrips_to_subscriber():
    """correlation_id propagates to the subscriber via subscribe_events."""
    bus = EventBus()
    seen: list[DomainEvent] = []

    async def handler(event: DomainEvent):
        seen.append(event)

    sub = bus.subscribe_events("trace.evt", handler)
    await bus.publish(
        "trace.evt", {"k": "v"}, correlation_id="trace-xyz", actor="svc-a"
    )
    await asyncio.sleep(0.02)

    assert len(seen) == 1
    assert seen[0].correlation_id == "trace-xyz"
    assert seen[0].actor == "svc-a"
    assert seen[0].payload == {"k": "v"}
    assert seen[0].event_type == "trace.evt"

    await sub.unsubscribe()
    await bus.close()


async def test_correlation_id_autogenerated_when_omitted():
    bus = EventBus()
    seen: list[DomainEvent] = []
    sub = bus.subscribe_events("x.evt", lambda e: seen.append(e) or _noop())
    await bus.publish("x.evt", {"a": 1})
    await asyncio.sleep(0.02)
    assert len(seen) == 1
    assert isinstance(seen[0].correlation_id, str)
    assert len(seen[0].correlation_id) >= 8  # uuid4
    await sub.unsubscribe()
    await bus.close()


async def _noop():
    return None


async def test_multiple_subscribers_same_event_type():
    bus = EventBus()
    a: list = []
    b: list = []
    sa = bus.subscribe("evt", lambda p: a.append(p) or _noop())
    sb = bus.subscribe("evt", lambda p: b.append(p) or _noop())
    await bus.publish("evt", {"n": 1})
    await asyncio.sleep(0.02)
    assert a == [{"n": 1}] and b == [{"n": 1}]
    await sa.unsubscribe()
    await bus.publish("evt", {"n": 2})
    await asyncio.sleep(0.02)
    assert a == [{"n": 1}]  # sa removed
    assert b == [{"n": 1}, {"n": 2}]  # sb still active
    await sb.unsubscribe()
    await bus.close()


async def test_handler_exception_does_not_break_other_handlers():
    bus = EventBus()
    good: list = []

    async def bad(_):
        raise RuntimeError("boom")

    async def good_h(p):
        good.append(p)

    s1 = bus.subscribe("evt", bad)
    s2 = bus.subscribe("evt", good_h)
    await bus.publish("evt", {"ok": True})
    await asyncio.sleep(0.02)
    assert good == [{"ok": True}]  # bad handler did not block good handler
    await s1.unsubscribe()
    await s2.unsubscribe()
    await bus.close()


# ---------------------------------------------------------------------------
# Acceptance: backend selection via env var, identical primitive shape
# ---------------------------------------------------------------------------


def test_create_backend_default_memory():
    be = create_backend()
    assert isinstance(be, InMemoryEventBackend)
    assert isinstance(be, EventBackend)


def test_create_backend_env_var(monkeypatch):
    monkeypatch.setenv("KAILASH_EVENTBUS_BACKEND", "memory")
    bus = EventBus()  # reads env var
    assert bus.backend_name == "InMemoryEventBackend"


def test_create_backend_unknown_raises():
    with pytest.raises(ValueError, match="unknown eventbus backend"):
        create_backend("rabbitmq")


def test_eventbus_accepts_backend_instance():
    backend = InMemoryEventBackend(max_subscribers=5)
    bus = EventBus(backend=backend)
    assert bus.backend_name == "InMemoryEventBackend"


def test_subscriber_limit_enforced():
    bus = EventBus(backend=InMemoryEventBackend(max_subscribers=1))
    bus.subscribe("e", lambda p: _noop())
    with pytest.raises(RuntimeError, match="subscriber limit reached"):
        bus.subscribe("e2", lambda p: _noop())


def test_publish_validation():
    bus = EventBus()
    import pytest as _pytest

    async def _run():
        with _pytest.raises(ValueError, match="event_type must be"):
            await bus.publish("", {})
        with _pytest.raises(ValueError, match="payload must be a dict"):
            await bus.publish("e", "not-a-dict")  # type: ignore[arg-type]

    asyncio.get_event_loop().run_until_complete(_run()) if False else None
    # run synchronously via a fresh loop to keep this a sync test
    asyncio.run(_run())


# ---------------------------------------------------------------------------
# Acceptance: WorkflowBuilder step publishes via the bus (real workflow run)
# ---------------------------------------------------------------------------


async def test_workflow_step_publishes_via_eventbus():
    """Tier 2: a WorkflowBuilder step publishes an event through the bus,
    a subscriber receives the original payload + correlation_id."""
    from kailash.runtime.local import LocalRuntime
    from kailash.workflow.builder import WorkflowBuilder

    bus = EventBus()
    received: list[DomainEvent] = []

    async def handler(event: DomainEvent):
        received.append(event)

    sub = bus.subscribe_events("workflow.order.created", handler)

    wf = WorkflowBuilder()
    wf.add_node(
        "EventPublishNode",
        "emit",
        {
            "event_bus": bus,
            "event_type": "workflow.order.created",
            "payload": {"order_id": "wf-1"},
            "correlation_id": "wf-trace-1",
        },
    )
    with LocalRuntime() as runtime:
        results, _run_id = runtime.execute(wf.build())

    await asyncio.sleep(0.05)

    assert results["emit"]["published"] is True
    assert results["emit"]["event_type_out"] == "workflow.order.created"
    assert results["emit"]["correlation_id_out"] == "wf-trace-1"
    assert len(received) == 1
    assert received[0].payload == {"order_id": "wf-1"}
    assert received[0].correlation_id == "wf-trace-1"

    await sub.unsubscribe()
    await bus.close()


async def test_eventpublishnode_registered_in_registry():
    """EventPublishNode resolves via NodeRegistry on plain import kailash."""
    from kailash.nodes.base import NodeRegistry

    cls = NodeRegistry.get("EventPublishNode")
    assert cls.__name__ == "EventPublishNode"


# ---------------------------------------------------------------------------
# Broker backend: Redis Streams (xfail without a live Redis)
# ---------------------------------------------------------------------------


def _redis_available() -> bool:
    try:
        import redis  # noqa: F401
    except ImportError:
        return False
    return (
        os.environ.get("KAILASH_EVENTBUS_REDIS_URL") is not None
        or os.environ.get("REDIS_URL") is not None
    )


def test_redis_backend_importable_behind_optional_extra():
    """The broker backend class is importable from the public surface
    even when no Redis server is running (implementation completeness)."""
    assert RedisStreamsEventBackend is not None
    # Constructing requires the redis package (declared optional extra).
    import importlib.util

    if importlib.util.find_spec("redis") is None:
        with pytest.raises(ImportError, match="requires the 'redis' extra"):
            RedisStreamsEventBackend()
    else:
        # redis pkg present: construction must not raise (no connection yet)
        be = RedisStreamsEventBackend(url="redis://localhost:6379/0")
        assert isinstance(be, EventBackend)


@pytest.mark.requires_redis
async def test_redis_backend_roundtrip():
    """Tier 2 broker round-trip — xfail if no live Redis is reachable."""
    import importlib.util

    if importlib.util.find_spec("redis") is None:
        pytest.xfail("redis package not installed (optional extra)")

    url = (
        os.environ.get("KAILASH_EVENTBUS_REDIS_URL")
        or os.environ.get("REDIS_URL")
        or "redis://localhost:6379/0"
    )
    try:
        import redis.asyncio as redis_async

        client = redis_async.from_url(url)
        await client.ping()
        await client.aclose()
    except Exception:
        pytest.xfail(
            "no live Redis reachable; broker backend implementation is "
            "complete and importable but cannot be exercised without infra"
        )

    bus = EventBus(backend="redis", redis_url=url)
    received: list = []

    async def handler(payload):
        received.append(payload)

    sub = bus.subscribe("redis.evt", handler)
    await asyncio.sleep(0.2)  # let consumer task spin up
    await bus.publish("redis.evt", {"r": 1}, correlation_id="rt-1")
    # poll up to ~3s for the streamed event
    for _ in range(30):
        if received:
            break
        await asyncio.sleep(0.1)

    assert received == [{"r": 1}]
    await sub.unsubscribe()
    await bus.close()
