# Copyright 2026 Terrene Foundation
# SPDX-License-Identifier: Apache-2.0
"""Re-export of the canonical :mod:`kailash.ml.errors` hierarchy.

The error hierarchy lives in kailash-core so every wave package
(kailash-dataflow, kailash-nexus, kailash-kaizen, kailash-align,
kailash-pact) can catch :class:`MLError` without depending on kailash-ml.
This module re-publishes the same classes under the ``kailash_ml.errors``
namespace so legacy imports continue to work.

**Identity preservation** — ``kailash_ml.errors.MLError is
kailash.ml.errors.MLError`` is ``True``. There are no class definitions in
this file; all names are re-imports. Per ``rules/orphan-detection.md §6``
this is an eager re-export — every ``__all__`` entry resolves at module
import time, not via ``__getattr__``.

See ``specs/kailash-core-ml-integration.md §3.5``.
"""
from __future__ import annotations

from kailash.ml.errors import (  # Fingerprint helper (classified-payload discipline); --- Root ---; --- 11 domain families ---; --- Cross-cutting (direct children of MLError) ---; --- TrackingError subclasses ---; --- AutologError subclasses ---; --- RLError subclasses ---; --- BackendError subclasses ---; --- DriftMonitorError subclasses ---; --- InferenceServerError subclasses ---; --- ModelRegistryError subclasses ---; --- FeatureStoreError subclasses ---; --- AutoMLError subclasses ---; --- DiagnosticsError subclasses ---; --- DashboardError subclasses ---
    ActorRequiredError,
    AliasNotFoundError,
    AliasOccupiedError,
    ArtifactEncryptionError,
    ArtifactSizeExceededError,
    AuthorizationError,
    AutologAttachError,
    AutologDetachError,
    AutologDoubleAttachError,
    AutologError,
    AutologNoAmbientRunError,
    AutologUnknownFrameworkError,
    AutoMLError,
    BackendError,
    BudgetExhaustedError,
    CrossTenantLineageError,
    DashboardError,
    DiagnosticsError,
    DLDiagnosticsStateError,
    DriftMonitorError,
    DriftThresholdError,
    EnsembleFailureError,
    EnvVarDeprecatedError,
    ErasureRefusedError,
    ExperimentNotFoundError,
    FeatureNotFoundError,
    FeatureNotYetSupportedError,
    FeatureStoreError,
    ImmutableGoldenReferenceError,
    InferenceServerError,
    InsufficientSamplesError,
    InsufficientTrialsError,
    InvalidInputSchemaError,
    InvalidTenantIdError,
    LineageNotImplementedError,
    LineageRequiredError,
    LiveStreamError,
    MetricValueError,
    MigrationFailedError,
    MigrationImportError,
    MigrationRequiredError,
    MLError,
    ModelLoadError,
    ModelNotFoundError,
    ModelRegistryError,
    ModelSignatureRequiredError,
    MultiTenantOpError,
    OnnxExportUnsupportedOpsError,
    ParamValueError,
    PointInTimeViolationError,
    ProtocolConformanceError,
    RateLimitExceededError,
    ReferenceNotFoundError,
    ReplayBufferUnderflowError,
    RewardModelRequiredError,
    RLEnvIncompatibleError,
    RLError,
    RLPolicyShapeMismatchError,
    RunNotFoundError,
    RunNotFoundInDashboardError,
    SeedReportError,
    ShadowDivergenceError,
    StaleFeatureError,
    TenantQuotaExceededError,
    TenantRequiredError,
    TrackerStoreInitError,
    TrackingError,
    UnknownTenantError,
    UnsupportedFamily,
    UnsupportedPrecision,
    UnsupportedTrainerError,
    WorkflowNodeMLContextError,
    ZeroVarianceReferenceError,
    fingerprint_classified_value,
)

__all__ = [
    "fingerprint_classified_value",
    "MLError",
    "TrackingError",
    "AutologError",
    "RLError",
    "BackendError",
    "DriftMonitorError",
    "InferenceServerError",
    "ModelRegistryError",
    "FeatureStoreError",
    "AutoMLError",
    "DiagnosticsError",
    "DashboardError",
    "UnsupportedTrainerError",
    "MultiTenantOpError",
    "MigrationFailedError",
    "MigrationRequiredError",
    "WorkflowNodeMLContextError",
    "EnvVarDeprecatedError",
    "MetricValueError",
    "ParamValueError",
    "ActorRequiredError",
    "TenantRequiredError",
    "RunNotFoundError",
    "ExperimentNotFoundError",
    "TrackerStoreInitError",
    "InvalidTenantIdError",
    "ModelSignatureRequiredError",
    "LineageRequiredError",
    "LineageNotImplementedError",
    "ArtifactEncryptionError",
    "ArtifactSizeExceededError",
    "AliasNotFoundError",
    "ErasureRefusedError",
    "MigrationImportError",
    "AutologNoAmbientRunError",
    "AutologUnknownFrameworkError",
    "AutologAttachError",
    "AutologDetachError",
    "AutologDoubleAttachError",
    "RLEnvIncompatibleError",
    "RLPolicyShapeMismatchError",
    "ReplayBufferUnderflowError",
    "RewardModelRequiredError",
    "FeatureNotYetSupportedError",
    "UnsupportedPrecision",
    "UnsupportedFamily",
    "ReferenceNotFoundError",
    "InsufficientSamplesError",
    "DriftThresholdError",
    "ZeroVarianceReferenceError",
    "ModelLoadError",
    "InvalidInputSchemaError",
    "RateLimitExceededError",
    "TenantQuotaExceededError",
    "ShadowDivergenceError",
    "OnnxExportUnsupportedOpsError",
    "ModelNotFoundError",
    "AliasOccupiedError",
    "CrossTenantLineageError",
    "ImmutableGoldenReferenceError",
    "FeatureNotFoundError",
    "StaleFeatureError",
    "PointInTimeViolationError",
    "BudgetExhaustedError",
    "InsufficientTrialsError",
    "EnsembleFailureError",
    "DLDiagnosticsStateError",
    "ProtocolConformanceError",
    "SeedReportError",
    "UnknownTenantError",
    "AuthorizationError",
    "LiveStreamError",
    "RunNotFoundInDashboardError",
]
