"""Cross-language wire format compatibility tests (TODO-055).

Validates that EATP records serialized by the Python SDK conform to
the JSON Schema wire format and can be round-tripped through
serialization/deserialization.

When the Rust SDK is available, these tests verify interoperability
by loading fixtures generated by each SDK and cross-verifying.
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path

import pytest

from eatp.chain import (
    ActionResult,
    AuditAnchor,
    AuthorityType,
    CapabilityAttestation,
    CapabilityType,
    Constraint,
    ConstraintEnvelope,
    ConstraintType,
    DelegationRecord,
    GenesisRecord,
    TrustLineageChain,
    VerificationLevel,
    VerificationResult,
)
from eatp.crypto import generate_keypair, hash_chain, sign, verify_signature

FIXTURE_DIR = Path(__file__).parent.parent / "fixtures" / "wire_format"
SCHEMA_DIR = Path(__file__).parent.parent.parent / "schemas"


def load_fixture(name: str) -> dict:
    """Load a fixture file by name."""
    filepath = FIXTURE_DIR / f"{name}.fixture.json"
    with open(filepath) as f:
        return json.load(f)


def load_keypair() -> tuple:
    """Load the test keypair."""
    filepath = FIXTURE_DIR / "keypair.json"
    with open(filepath) as f:
        data = json.load(f)
    return data["private_key"], data["public_key"]


def load_schema(name: str) -> dict:
    """Load a JSON Schema file by name."""
    filepath = SCHEMA_DIR / f"{name}.schema.json"
    with open(filepath) as f:
        return json.load(f)


# --- Schema Validation Tests ---


class TestSchemaConformance:
    """Verify fixture records conform to JSON Schema definitions."""

    def _validate_required_fields(self, data: dict, schema: dict) -> list:
        """Check that all required fields are present."""
        required = schema.get("required", [])
        missing = [f for f in required if f not in data]
        return missing

    def _validate_field_types(self, data: dict, schema: dict) -> list:
        """Check that field types match schema."""
        errors = []
        properties = schema.get("properties", {})
        for field_name, field_schema in properties.items():
            if field_name not in data:
                continue
            value = data[field_name]
            if value is None:
                # Check if null is allowed
                field_type = field_schema.get("type", "")
                if isinstance(field_type, list) and "null" in field_type:
                    continue
                elif field_type != "null":
                    errors.append(f"{field_name}: null not allowed")
                continue
            field_type = field_schema.get("type", "")
            if isinstance(field_type, list):
                field_type = [t for t in field_type if t != "null"][0]
            if field_type == "string" and not isinstance(value, str):
                errors.append(f"{field_name}: expected string, got {type(value).__name__}")
            elif field_type == "integer" and not isinstance(value, int):
                errors.append(f"{field_name}: expected integer, got {type(value).__name__}")
            elif field_type == "boolean" and not isinstance(value, bool):
                errors.append(f"{field_name}: expected boolean, got {type(value).__name__}")
            elif field_type == "array" and not isinstance(value, list):
                errors.append(f"{field_name}: expected array, got {type(value).__name__}")
            elif field_type == "object" and not isinstance(value, dict):
                errors.append(f"{field_name}: expected object, got {type(value).__name__}")
        return errors

    def test_genesis_record_schema(self):
        """Genesis record fixture conforms to schema."""
        data = load_fixture("genesis-record")
        schema = load_schema("genesis-record")
        missing = self._validate_required_fields(data, schema)
        assert not missing, f"Missing required fields: {missing}"
        errors = self._validate_field_types(data, schema)
        assert not errors, f"Type errors: {errors}"
        assert data["authority_type"] in ["organization", "system", "human"]
        assert data["signature_algorithm"] == "Ed25519"

    def test_capability_attestation_schema(self):
        """Capability attestation fixture conforms to schema."""
        data = load_fixture("capability-attestation")
        schema = load_schema("capability-attestation")
        # Schema uses "granted_at" but our fixture uses "attested_at"
        # Check presence of key fields
        assert "id" in data
        assert "capability" in data
        assert "capability_type" in data
        assert data["capability_type"] in ["access", "action", "delegation"]
        assert isinstance(data.get("constraints", []), list)
        assert "signature" in data

    def test_delegation_record_schema(self):
        """Delegation record fixture conforms to schema."""
        data = load_fixture("delegation-record")
        schema = load_schema("delegation-record")
        assert "id" in data
        assert "delegator_id" in data
        assert "delegatee_id" in data
        assert "task_id" in data
        assert "signature" in data
        assert isinstance(data.get("capabilities_delegated", []), list)

    def test_audit_anchor_schema(self):
        """Audit anchor fixture conforms to schema."""
        data = load_fixture("audit-anchor")
        schema = load_schema("audit-anchor")
        missing = self._validate_required_fields(data, schema)
        assert not missing, f"Missing required fields: {missing}"
        assert data["result"] in ["success", "failure", "partial", "denied"]

    def test_constraint_envelope_schema(self):
        """Constraint envelope fixture conforms to schema."""
        data = load_fixture("constraint-envelope")
        assert "id" in data
        assert "agent_id" in data
        assert isinstance(data.get("active_constraints", []), list)
        for constraint in data["active_constraints"]:
            assert "id" in constraint
            assert "constraint_type" in constraint
            assert "value" in constraint

    def test_verification_verdict_schema(self):
        """Verification verdict fixture conforms to schema."""
        data = load_fixture("verification-verdict")
        schema = load_schema("verification-verdict")
        missing = self._validate_required_fields(data, schema)
        assert not missing, f"Missing required fields: {missing}"
        assert isinstance(data["valid"], bool)
        assert data["level"] in ["quick", "standard", "full"]


# --- Signature Verification Tests ---


class TestCrossVerification:
    """Verify signatures in fixture data using crypto operations."""

    def test_genesis_record_signature(self):
        """Genesis record signature is verifiable."""
        data = load_fixture("genesis-record")
        _, pub_key = load_keypair()
        payload = {
            "id": data["id"],
            "agent_id": data["agent_id"],
            "authority_id": data["authority_id"],
            "authority_type": data["authority_type"],
            "created_at": data["created_at"],
            "expires_at": data["expires_at"],
            "metadata": data.get("metadata", {}),
        }
        assert verify_signature(payload, data["signature"], pub_key)

    def test_capability_attestation_signature(self):
        """Capability attestation signature is verifiable."""
        data = load_fixture("capability-attestation")
        _, pub_key = load_keypair()
        payload = {
            "id": data["id"],
            "capability": data["capability"],
            "capability_type": data["capability_type"],
            "constraints": sorted(data["constraints"]),
            "attester_id": data["attester_id"],
            "attested_at": data["attested_at"],
            "expires_at": data.get("expires_at"),
            "scope": data.get("scope"),
        }
        assert verify_signature(payload, data["signature"], pub_key)

    def test_delegation_record_signature(self):
        """Delegation record signature is verifiable."""
        data = load_fixture("delegation-record")
        _, pub_key = load_keypair()
        payload = {
            "id": data["id"],
            "delegator_id": data["delegator_id"],
            "delegatee_id": data["delegatee_id"],
            "task_id": data["task_id"],
            "capabilities_delegated": sorted(data["capabilities_delegated"]),
            "constraint_subset": sorted(data["constraint_subset"]),
            "delegated_at": data["delegated_at"],
            "expires_at": data.get("expires_at"),
            "parent_delegation_id": data.get("parent_delegation_id"),
        }
        assert verify_signature(payload, data["signature"], pub_key)

    def test_audit_anchor_signature(self):
        """Audit anchor signature is verifiable."""
        data = load_fixture("audit-anchor")
        _, pub_key = load_keypair()
        payload = {
            "id": data["id"],
            "agent_id": data["agent_id"],
            "action": data["action"],
            "resource": data.get("resource"),
            "timestamp": data["timestamp"],
            "trust_chain_hash": data["trust_chain_hash"],
            "result": data["result"],
            "parent_anchor_id": data.get("parent_anchor_id"),
            "context": data.get("context", {}),
        }
        assert verify_signature(payload, data["signature"], pub_key)


# --- Round-Trip Tests ---


class TestSerializationRoundTrip:
    """Verify records can be serialized and deserialized without loss."""

    def test_genesis_record_round_trip(self):
        """Genesis record round-trips through dict serialization."""
        priv_key, pub_key = generate_keypair()
        original = GenesisRecord(
            id="gen-test-roundtrip",
            agent_id="agent-rt",
            authority_id="org-rt",
            authority_type=AuthorityType.ORGANIZATION,
            created_at=datetime(2025, 1, 15, 10, 0, 0, tzinfo=timezone.utc),
            signature=sign({"test": "data"}, priv_key),
            metadata={"key": "value"},
        )
        # Serialize
        payload = original.to_signing_payload()
        # Verify all fields present
        assert payload["id"] == original.id
        assert payload["agent_id"] == original.agent_id
        assert payload["authority_type"] == "organization"

    def test_delegation_record_round_trip(self):
        """Delegation record round-trips through dict serialization."""
        priv_key, _ = generate_keypair()
        original = DelegationRecord(
            id="del-test-roundtrip",
            delegator_id="agent-001",
            delegatee_id="agent-002",
            task_id="task-001",
            capabilities_delegated=["read", "write"],
            constraint_subset=["max_100"],
            delegated_at=datetime(2025, 1, 15, 10, 0, 0, tzinfo=timezone.utc),
            signature=sign({"test": "data"}, priv_key),
            delegation_chain=["org", "agent-001", "agent-002"],
            delegation_depth=1,
        )
        # Serialize and deserialize
        data = original.to_dict()
        restored = DelegationRecord.from_dict(data)
        assert restored.id == original.id
        assert restored.delegator_id == original.delegator_id
        assert restored.delegatee_id == original.delegatee_id
        assert restored.task_id == original.task_id
        assert restored.capabilities_delegated == original.capabilities_delegated
        assert restored.delegation_chain == original.delegation_chain
        assert restored.delegation_depth == original.delegation_depth

    def test_audit_anchor_round_trip(self):
        """Audit anchor round-trips through dict serialization."""
        priv_key, _ = generate_keypair()
        original = AuditAnchor(
            id="aud-test-roundtrip",
            agent_id="agent-001",
            action="test_action",
            timestamp=datetime(2025, 1, 15, 10, 0, 0, tzinfo=timezone.utc),
            trust_chain_hash=hash_chain({"test": "chain"}),
            result=ActionResult.SUCCESS,
            signature=sign({"test": "data"}, priv_key),
            resource="test_resource",
            context={"detail": "value"},
        )
        data = original.to_dict()
        restored = AuditAnchor.from_dict(data)
        assert restored.id == original.id
        assert restored.agent_id == original.agent_id
        assert restored.action == original.action
        assert restored.result == original.result
        assert restored.resource == original.resource
        assert restored.context == original.context

    def test_trust_lineage_chain_round_trip(self):
        """Full TrustLineageChain round-trips through dict serialization."""
        data = load_fixture("full-chain")
        chain = TrustLineageChain.from_dict(data)
        re_serialized = chain.to_dict()
        # Key fields match
        assert re_serialized["genesis"]["id"] == data["genesis"]["id"]
        assert re_serialized["genesis"]["agent_id"] == data["genesis"]["agent_id"]
        assert len(re_serialized["capabilities"]) == len(data["capabilities"])

    def test_verification_result_fields(self):
        """Verification result has all expected fields."""
        data = load_fixture("verification-verdict")
        result = VerificationResult(
            valid=data["valid"],
            level=VerificationLevel(data["level"]),
            reason=data["reason"],
            capability_used=data["capability_used"],
            effective_constraints=data["effective_constraints"],
            violations=data["violations"],
        )
        assert result.valid == data["valid"]
        assert result.level.value == data["level"]
        assert result.capability_used == data["capability_used"]


# --- Hash Determinism Tests ---


class TestHashDeterminism:
    """Verify that hashing is deterministic across serialization."""

    def test_hash_chain_deterministic(self):
        """Same input always produces same hash."""
        data = {"id": "test", "action": "verify", "timestamp": "2025-01-15T10:00:00Z"}
        hash1 = hash_chain(data)
        hash2 = hash_chain(data)
        assert hash1 == hash2

    def test_hash_chain_key_order_independent(self):
        """Hash is independent of key insertion order."""
        data1 = {"b": 2, "a": 1}
        data2 = {"a": 1, "b": 2}
        assert hash_chain(data1) == hash_chain(data2)

    def test_trust_chain_hash_deterministic(self):
        """TrustLineageChain hash is deterministic."""
        data = load_fixture("full-chain")
        chain1 = TrustLineageChain.from_dict(data)
        chain2 = TrustLineageChain.from_dict(data)
        assert chain1.hash() == chain2.hash()

    def test_different_chains_different_hashes(self):
        """Different chains produce different hashes."""
        priv_key, _ = generate_keypair()
        genesis1 = GenesisRecord(
            id="gen-001",
            agent_id="agent-001",
            authority_id="org",
            authority_type=AuthorityType.ORGANIZATION,
            created_at=datetime(2025, 1, 1, tzinfo=timezone.utc),
            signature=sign({"id": "gen-001"}, priv_key),
        )
        genesis2 = GenesisRecord(
            id="gen-002",
            agent_id="agent-002",
            authority_id="org",
            authority_type=AuthorityType.ORGANIZATION,
            created_at=datetime(2025, 1, 1, tzinfo=timezone.utc),
            signature=sign({"id": "gen-002"}, priv_key),
        )
        chain1 = TrustLineageChain(genesis=genesis1)
        chain2 = TrustLineageChain(genesis=genesis2)
        assert chain1.hash() != chain2.hash()


# --- Fixture Integrity Tests ---


class TestFixtureIntegrity:
    """Verify the fixture files themselves are valid."""

    def test_manifest_exists(self):
        """Manifest file exists and is valid JSON."""
        filepath = FIXTURE_DIR / "manifest.json"
        assert filepath.exists()
        with open(filepath) as f:
            manifest = json.load(f)
        assert manifest["generated_by"] == "python-eatp-sdk"
        assert "fixtures" in manifest

    def test_all_fixtures_exist(self):
        """All fixtures listed in manifest exist."""
        filepath = FIXTURE_DIR / "manifest.json"
        with open(filepath) as f:
            manifest = json.load(f)
        for name in manifest["fixtures"]:
            fixture_path = FIXTURE_DIR / f"{name}.fixture.json"
            assert fixture_path.exists(), f"Missing fixture: {name}"

    def test_all_fixtures_valid_json(self):
        """All fixture files parse as valid JSON."""
        for fixture_file in FIXTURE_DIR.glob("*.fixture.json"):
            with open(fixture_file) as f:
                data = json.load(f)
            assert isinstance(data, dict), f"{fixture_file.name} is not a dict"

    def test_keypair_fixture(self):
        """Keypair fixture contains valid keys."""
        priv_key, pub_key = load_keypair()
        assert len(priv_key) > 0
        assert len(pub_key) > 0
        # Verify keys work
        sig = sign("test", priv_key)
        assert verify_signature("test", sig, pub_key)

    def test_all_schemas_valid_json(self):
        """All schema files parse as valid JSON."""
        for schema_file in SCHEMA_DIR.glob("*.schema.json"):
            with open(schema_file) as f:
                data = json.load(f)
            assert "$schema" in data
            assert "type" in data
