# Copyright 2026 Terrene Foundation
# SPDX-License-Identifier: Apache-2.0
"""Tier 1 unit tests for DLDiagnostics — fast, no I/O.

Covers input validation, run_id semantics, and the plotly extras-gating
loud-fail contract. Integration-style tests (real training step, real
Protocol dispatch) live in tests/integration/test_dl_diagnostics_wiring.py.
"""
from __future__ import annotations

import pytest

torch = pytest.importorskip("torch")
nn = pytest.importorskip("torch.nn")

from kailash_ml.diagnostics import DLDiagnostics  # noqa: E402
from kailash_ml.diagnostics import dl as dl_mod  # noqa: E402


# ---------------------------------------------------------------------------
# __init__ validation
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_init_rejects_non_module_input() -> None:
    """`__init__` raises TypeError when `model` is not an `nn.Module`.

    Routes through the protocol-level input validation documented in
    the class contract (Raises: TypeError).
    """
    with pytest.raises(TypeError, match="requires an nn.Module"):
        DLDiagnostics("not a module")  # type: ignore[arg-type]


@pytest.mark.unit
def test_init_rejects_threshold_below_zero() -> None:
    """`dead_neuron_threshold` MUST lie in the open interval (0, 1)."""
    model = nn.Linear(4, 2)
    with pytest.raises(ValueError, match="dead_neuron_threshold must be in"):
        DLDiagnostics(model, dead_neuron_threshold=0.0)


@pytest.mark.unit
def test_init_rejects_threshold_equal_to_one() -> None:
    """`dead_neuron_threshold=1.0` rejected (interval is open)."""
    model = nn.Linear(4, 2)
    with pytest.raises(ValueError, match="dead_neuron_threshold must be in"):
        DLDiagnostics(model, dead_neuron_threshold=1.0)


@pytest.mark.unit
def test_init_rejects_window_below_one() -> None:
    """`window` MUST be >= 1."""
    model = nn.Linear(4, 2)
    with pytest.raises(ValueError, match="window must be >= 1"):
        DLDiagnostics(model, window=0)


@pytest.mark.unit
def test_init_rejects_empty_run_id() -> None:
    """An empty-string `run_id` is rejected; user-supplied IDs MUST have content."""
    model = nn.Linear(4, 2)
    with pytest.raises(ValueError, match="run_id"):
        DLDiagnostics(model, run_id="")


# ---------------------------------------------------------------------------
# run_id semantics
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_run_id_autogenerated_when_omitted() -> None:
    """`DLDiagnostics(model)` generates a UUID-shaped `run_id`."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model)
    assert isinstance(diag.run_id, str)
    # UUID4 hex = 32 chars of [0-9a-f].
    assert len(diag.run_id) == 32
    assert all(c in "0123456789abcdef" for c in diag.run_id)


@pytest.mark.unit
def test_run_id_unique_across_sessions() -> None:
    """Two separately-constructed sessions get distinct auto-generated IDs."""
    model = nn.Linear(4, 2)
    a = DLDiagnostics(model)
    b = DLDiagnostics(model)
    assert a.run_id != b.run_id


@pytest.mark.unit
def test_run_id_kwarg_overrides_default() -> None:
    """An explicit `run_id` kwarg is preserved verbatim."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model, run_id="explicit-run-id")
    assert diag.run_id == "explicit-run-id"


# ---------------------------------------------------------------------------
# Validation bounds — boundary values that SHOULD succeed
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_init_accepts_window_of_one() -> None:
    """`window=1` is the minimum valid value."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model, window=1)
    assert diag.window == 1


@pytest.mark.unit
def test_init_accepts_threshold_midpoint() -> None:
    """Default threshold of 0.5 is always valid."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model, dead_neuron_threshold=0.5)
    assert diag.dead_neuron_threshold == 0.5


# ---------------------------------------------------------------------------
# Plotly extras-gating — plot_*() raises ImportError naming [dl]
# ---------------------------------------------------------------------------
#
# Because plotly happens to be in base deps today, we simulate the
# missing-extra scenario by monkey-patching the lazy loader to raise.
# This verifies the loud-fail contract without uninstalling plotly.


@pytest.mark.unit
def test_plot_loss_curves_raises_loudly_when_plotly_missing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`plot_loss_curves` raises ImportError naming `[dl]` when plotly is absent."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model)

    def _no_plotly() -> None:
        raise ImportError(
            "Plotting methods require plotly. Install the deep-learning extras: "
            "pip install kailash-ml[dl]"
        )

    monkeypatch.setattr(dl_mod, "_require_plotly", _no_plotly)
    with pytest.raises(ImportError, match=r"kailash-ml\[dl\]"):
        diag.plot_loss_curves()


@pytest.mark.unit
def test_plot_gradient_flow_raises_loudly_when_plotly_missing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`plot_gradient_flow` raises ImportError naming `[dl]` when plotly is absent."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model)

    def _no_plotly() -> None:
        raise ImportError(
            "Plotting methods require plotly. Install the deep-learning extras: "
            "pip install kailash-ml[dl]"
        )

    monkeypatch.setattr(dl_mod, "_require_plotly", _no_plotly)
    with pytest.raises(ImportError, match=r"kailash-ml\[dl\]"):
        diag.plot_gradient_flow()


@pytest.mark.unit
def test_plot_activation_stats_raises_loudly_when_plotly_missing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`plot_activation_stats` raises ImportError naming `[dl]` when plotly is absent."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model)

    def _no_plotly() -> None:
        raise ImportError(
            "Plotting methods require plotly. Install the deep-learning extras: "
            "pip install kailash-ml[dl]"
        )

    monkeypatch.setattr(dl_mod, "_require_plotly", _no_plotly)
    with pytest.raises(ImportError, match=r"kailash-ml\[dl\]"):
        diag.plot_activation_stats()


@pytest.mark.unit
def test_plot_dead_neurons_raises_loudly_when_plotly_missing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`plot_dead_neurons` raises ImportError naming `[dl]` when plotly is absent."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model)

    def _no_plotly() -> None:
        raise ImportError(
            "Plotting methods require plotly. Install the deep-learning extras: "
            "pip install kailash-ml[dl]"
        )

    monkeypatch.setattr(dl_mod, "_require_plotly", _no_plotly)
    with pytest.raises(ImportError, match=r"kailash-ml\[dl\]"):
        diag.plot_dead_neurons()


@pytest.mark.unit
def test_plot_training_dashboard_raises_loudly_when_plotly_missing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`plot_training_dashboard` raises ImportError naming `[dl]` when plotly is absent."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model)

    def _no_plotly() -> None:
        raise ImportError(
            "Plotting methods require plotly. Install the deep-learning extras: "
            "pip install kailash-ml[dl]"
        )

    monkeypatch.setattr(dl_mod, "_require_plotly", _no_plotly)
    with pytest.raises(ImportError, match=r"kailash-ml\[dl\]"):
        diag.plot_training_dashboard()


# ---------------------------------------------------------------------------
# report() + dataframe accessors — empty-state contract
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_report_on_empty_session_returns_unknown_findings() -> None:
    """A session with no `track_*()` calls still returns a well-formed dict."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model)
    report = diag.report()
    assert report["batches"] == 0
    assert report["epochs"] == 0
    assert report["gradient_flow"]["severity"] == "UNKNOWN"
    assert report["dead_neurons"]["severity"] == "UNKNOWN"
    assert report["loss_trend"]["severity"] == "UNKNOWN"
    assert report["run_id"] == diag.run_id


@pytest.mark.unit
def test_empty_dataframe_accessors_return_zero_height() -> None:
    """All `*_df()` accessors return empty polars DataFrames on a fresh session."""
    model = nn.Linear(4, 2)
    diag = DLDiagnostics(model)
    assert diag.batches_df().height == 0
    assert diag.epochs_df().height == 0
    assert diag.gradients_df().height == 0
    assert diag.activations_df().height == 0
    assert diag.dead_neurons_df().height == 0


# ---------------------------------------------------------------------------
# lr_range_test input validation
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_lr_range_test_rejects_missing_loss_fn() -> None:
    """`lr_range_test` MUST NOT have a silent-default loss_fn."""
    model = nn.Linear(4, 2)
    with pytest.raises(ValueError, match="loss_fn is required"):
        DLDiagnostics.lr_range_test(model, dataloader=[])


@pytest.mark.unit
def test_lr_range_test_rejects_steps_below_two() -> None:
    """`lr_range_test` needs at least 2 steps for a meaningful sweep."""
    model = nn.Linear(4, 2)
    with pytest.raises(ValueError, match="steps must be >= 2"):
        DLDiagnostics.lr_range_test(model, dataloader=[], loss_fn=nn.MSELoss(), steps=1)


@pytest.mark.unit
def test_lr_range_test_rejects_inverted_lr_range() -> None:
    """`lr_max` MUST be strictly greater than `lr_min`."""
    model = nn.Linear(4, 2)
    with pytest.raises(ValueError, match="0 < lr_min < lr_max"):
        DLDiagnostics.lr_range_test(
            model, dataloader=[], loss_fn=nn.MSELoss(), lr_min=1.0, lr_max=0.1
        )
