"""Regression tests for issue #2092 — kaizen EncryptionProvider invented its AES key.

Before the fix, ``EncryptionProvider(key=None)`` generated a fresh AES-256-GCM
key via ``AESGCM.generate_key`` and continued **entirely silently** — no error,
no warning, not even an INFO line. The key lived only inside that process, so
anything encrypted under it was unrecoverable after the process exited, and in a
multi-replica deployment a value written by replica A could not be read by
replica B. Because nothing was logged, the first symptom was unreadable data
with nothing in the logs pointing at why.

The default propagated through two wrappers, which is how it stayed hidden:

- ``KeyManager.__init__`` took no key parameter at all and called
  ``EncryptionProvider()`` bare for every key version, so ``re_encrypt`` — the
  documented migration path — destroyed the pre-rotation data too.
- ``FieldEncryptor(sensitive_fields=[...], key=None)`` forwarded ``None``
  straight through, so a call that reads as fully configured silently got a
  throwaway key for PII.

Third instance of the same class as #2041 (``SecretManager``, PR #2063) and
#2083 (``JWTAuthManager``), each using a different generator.

Each test docstring names the result it would produce if the property under test
were absent, so a green here is readable as evidence rather than as a pass.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

import pytest

from kaizen.security import encryption as encryption_module
from kaizen.security.encryption import (
    MIN_PASSPHRASE_LENGTH,
    EncryptionKeyNotConfiguredError,
    EncryptionProvider,
    FieldEncryptor,
    KeyManager,
)

#: A passphrase an operator would plausibly configure.
CONFIGURED_PASSPHRASE = "a-configured-kaizen-encryption-passphrase"

#: A raw 32-byte key, the other accepted shape.
CONFIGURED_RAW_KEY = b"0123456789abcdef0123456789abcdef"


@pytest.fixture(autouse=True)
def _reset_one_time_signal():
    """Clear the ``lru_cache``d one-time signal between tests.

    Without this only the first test to trigger the signal could observe it, and
    every later assertion would read a cache hit as "no signal was emitted".
    """
    warn = getattr(encryption_module, "_warn_ephemeral_encryption_key", None)
    if warn is not None and hasattr(warn, "cache_clear"):
        warn.cache_clear()
    yield
    if warn is not None and hasattr(warn, "cache_clear"):
        warn.cache_clear()


@pytest.fixture(autouse=True)
def _no_ambient_key(monkeypatch):
    """Ensure the environment wiring is absent unless a test sets it.

    A developer machine exporting ``KAIZEN_ENCRYPTION_KEY`` would otherwise turn
    every unconfigured-path test green for the wrong reason.
    """
    monkeypatch.delenv("KAIZEN_ENCRYPTION_KEY", raising=False)


@pytest.mark.regression
def test_the_module_under_test_is_this_worktree():
    """Provenance guard.

    A bare interpreter in this worktree can resolve ``kaizen`` from a different
    checkout or from site-packages, in which case every other assertion here
    would measure the wrong tree while still printing green. Falsifying result:
    a path outside this worktree.
    """
    resolved = Path(encryption_module.__file__).resolve()
    expected_root = Path(__file__).resolve().parents[2]
    assert resolved.is_relative_to(expected_root), (
        f"kaizen.security.encryption resolved to {resolved}, outside "
        f"{expected_root}. These tests would be exercising a different checkout."
    )


@pytest.mark.regression
def test_provider_on_the_default_path_refuses_to_invent_a_key():
    """The defect: ``EncryptionProvider()`` bare must not mint its own key.

    Falsifying result if the fix were absent: no exception, and ``provider.key``
    holds 32 freshly generated bytes.
    """
    with pytest.raises(Exception) as excinfo:
        EncryptionProvider()

    message = str(excinfo.value)
    assert (
        "KAIZEN_ENCRYPTION_KEY" in message
    ), f"The error must name the environment variable that fixes it. Got: {message}"
    assert "key=" in message, "The error must name the constructor wiring."


@pytest.mark.regression
def test_key_manager_on_the_default_path_refuses_to_invent_a_key():
    """``KeyManager()`` took no key parameter at all — every version was throwaway.

    Falsifying result if the fix were absent: construction succeeds and
    ``manager.keys[1]`` holds a process-local key.
    """
    with pytest.raises(Exception) as excinfo:
        KeyManager()

    assert "KAIZEN_ENCRYPTION_KEY" in str(excinfo.value)


@pytest.mark.regression
def test_field_encryptor_does_not_launder_the_default_through_its_wrapper():
    """The propagation shape that hid the primary instance.

    ``FieldEncryptor(sensitive_fields=["ssn"])`` reads as fully configured. The
    ``key=None`` default forwarded straight into ``EncryptionProvider``, so PII
    was encrypted under a key that died with the process.

    Falsifying result if only the provider were fixed and not its wrapper: no
    exception here.
    """
    with pytest.raises(Exception) as excinfo:
        FieldEncryptor(sensitive_fields=["ssn"])

    assert "KAIZEN_ENCRYPTION_KEY" in str(excinfo.value)


@pytest.mark.regression
def test_environment_variable_supplies_the_key_with_no_code_change():
    """The wiring the error message names must actually work.

    The assertion is that the provider derives THAT key, not merely that it
    round-trips: a provider that ignored the variable and generated its own key
    would also encrypt and decrypt its own data happily, so a round-trip alone
    cannot tell the two apart.

    Falsifying result if the read were absent: the constructor raises, or the
    resolved key differs from the one the passphrase derives.
    """
    os.environ["KAIZEN_ENCRYPTION_KEY"] = CONFIGURED_PASSPHRASE
    try:
        provider = EncryptionProvider()
        assert provider.decrypt(provider.encrypt("hello")) == "hello"
        assert provider.key == EncryptionProvider(key=CONFIGURED_PASSPHRASE).key, (
            "The provider did not derive its key from the environment variable; "
            "it used its own value, so the variable named in the error message "
            "is not actually wired."
        )
    finally:
        del os.environ["KAIZEN_ENCRYPTION_KEY"]


@pytest.mark.regression
def test_the_loud_signal_names_the_current_constants(caplog):
    """The signal spells its variable name literally, so it can drift.

    ``_warn_ephemeral_encryption_key`` writes ``KAIZEN_ENCRYPTION_KEY`` as a
    literal rather than interpolating :data:`KAIZEN_ENCRYPTION_KEY_ENV`, because
    CodeQL reads a constant with that name as key material flowing into a log
    sink. The cost is that renaming the constant would leave the message
    pointing at a variable that no longer exists.

    Falsifying result if the two drifted: the constant's value is absent from
    the emitted message.
    """
    with caplog.at_level(logging.DEBUG, logger=encryption_module.__name__):
        EncryptionProvider(allow_ephemeral_key=True)

    errors = [r for r in caplog.records if r.levelno >= logging.ERROR]
    assert errors, "No signal emitted; the drift guard has nothing to check."
    assert encryption_module.KAIZEN_ENCRYPTION_KEY_ENV in errors[0].getMessage(), (
        f"The signal names a variable that is no longer "
        f"{encryption_module.KAIZEN_ENCRYPTION_KEY_ENV}: {errors[0].getMessage()}"
    )


@pytest.mark.regression
def test_two_providers_from_the_same_configured_key_interoperate():
    """The multi-replica property, stated positively (AC of #2092).

    A value encrypted by one replica MUST be readable by another configured from
    the same source. Before the fix each replica generated its own key and this
    failed with ``InvalidTag``.

    Falsifying result if the property were absent: ``InvalidTag`` on decrypt.
    """
    replica_a = EncryptionProvider(key=CONFIGURED_RAW_KEY)
    replica_b = EncryptionProvider(key=CONFIGURED_RAW_KEY)

    sealed = replica_a.encrypt({"ssn": "123-45-6789"})
    assert replica_b.decrypt(sealed) == {"ssn": "123-45-6789"}


@pytest.mark.regression
def test_two_providers_from_the_same_passphrase_interoperate_across_restarts():
    """A passphrase must derive the SAME key every time, or it is not durable.

    A per-process random salt would make each derivation unique and reproduce
    the very defect this issue is about, one layer down.

    Falsifying result if derivation were salted per process: ``InvalidTag``.
    """
    os.environ["KAIZEN_ENCRYPTION_KEY"] = CONFIGURED_PASSPHRASE
    try:
        before_restart = EncryptionProvider()
        sealed = before_restart.encrypt("survives")
        after_restart = EncryptionProvider()
        assert after_restart.decrypt(sealed) == "survives"
    finally:
        del os.environ["KAIZEN_ENCRYPTION_KEY"]


@pytest.mark.regression
def test_key_manager_versions_are_distinct_yet_survive_a_restart():
    """Rotation must produce a DIFFERENT key per version, and a DURABLE one.

    Two managers configured from the same master key model the same service
    before and after a restart: data written under version 1 must still read
    back, and version 2 must not be the same key as version 1 (or rotation
    would be cosmetic).

    Falsifying result: ``InvalidTag`` across managers (not durable), or equal
    per-version keys (rotation does nothing).
    """
    before_restart = KeyManager(key=CONFIGURED_RAW_KEY)
    sealed_v1 = before_restart.encrypt("v1 data")
    before_restart.rotate_key(2)
    sealed_v2 = before_restart.encrypt("v2 data")

    assert (
        before_restart.keys[1].key != before_restart.keys[2].key
    ), "Rotation produced the same key material for both versions."

    after_restart = KeyManager(key=CONFIGURED_RAW_KEY)
    after_restart.rotate_key(2)
    assert after_restart.decrypt(sealed_v1) == "v1 data"
    assert after_restart.decrypt(sealed_v2) == "v2 data"


@pytest.mark.regression
def test_field_encryptor_round_trips_when_configured():
    """Negative control: the configured path must keep working.

    Falsifying result: a change that "fixed" the defect by breaking encryption
    outright would fail here while passing every raise-assertion above.
    """
    encryptor = FieldEncryptor(sensitive_fields=["ssn"], key=CONFIGURED_RAW_KEY)
    sealed = encryptor.encrypt_fields({"ssn": "123-45-6789", "name": "Kim"})

    assert sealed["ssn"].startswith("encrypted:")
    assert sealed["name"] == "Kim", "Non-sensitive fields must be untouched."

    reader = FieldEncryptor(sensitive_fields=["ssn"], key=CONFIGURED_RAW_KEY)
    assert reader.decrypt_fields(sealed)["ssn"] == "123-45-6789"


@pytest.mark.regression
def test_explicit_opt_in_still_generates_but_announces_it_at_error_level(caplog):
    """Dev ergonomics retained, but as an EXPLICIT opt-in, and loudly.

    ``security.md`` § Secure-Default For A New Security Feature permits the
    generate-and-continue path only behind a loud one-time signal naming the
    protection that is off and its exact wiring. This path previously emitted
    nothing at all.

    Falsifying result if the fix were absent: no record at ERROR, or a record
    naming neither the durability consequence nor the wiring.
    """
    with caplog.at_level(logging.DEBUG, logger=encryption_module.__name__):
        provider = EncryptionProvider(allow_ephemeral_key=True)

    assert provider.key, "The opt-in path must still produce a usable key."

    errors = [r for r in caplog.records if r.levelno >= logging.ERROR]
    assert errors, (
        "The ephemeral-key path must announce itself at ERROR. Records seen: "
        f"{[(r.levelname, r.getMessage()) for r in caplog.records]}"
    )
    message = errors[0].getMessage()
    assert "KAIZEN_ENCRYPTION_KEY" in message, "The signal must name the wiring."
    assert "restart" in message.lower(), "The signal must name the consequence."


@pytest.mark.regression
def test_the_loud_signal_fires_once_per_process_not_once_per_instance(caplog):
    """A per-instance line from a library is a line operators learn to filter.

    Falsifying result if the ``lru_cache`` were absent: two ERROR records.
    """
    with caplog.at_level(logging.DEBUG, logger=encryption_module.__name__):
        EncryptionProvider(allow_ephemeral_key=True)
        EncryptionProvider(allow_ephemeral_key=True)

    errors = [r for r in caplog.records if r.levelno >= logging.ERROR]
    assert len(errors) == 1, (
        f"Expected exactly one process-wide signal, got {len(errors)}: "
        f"{[r.getMessage() for r in errors]}"
    )


@pytest.mark.regression
def test_the_signal_never_carries_the_generated_key_material(caplog):
    """A fix that fails loudly must not itself print the key.

    Falsifying result: the generated key appears in a log record, in raw or hex
    form — which would convert a durability bug into a disclosure bug.
    """
    with caplog.at_level(logging.DEBUG, logger=encryption_module.__name__):
        provider = EncryptionProvider(allow_ephemeral_key=True)

    key_hex = provider.key.hex()
    for record in caplog.records:
        text = record.getMessage()
        assert key_hex not in text, "The generated key leaked into a log record (hex)."
        assert (
            str(provider.key) not in text
        ), "The generated key leaked into a log record."


@pytest.mark.regression
def test_a_configured_provider_emits_no_ephemeral_key_signal(caplog):
    """Negative control.

    A change that "fixed" the defect by shouting on every construction would be
    indistinguishable from the real fix in every other test here.

    Falsifying result: an ERROR record from a properly configured provider.
    """
    with caplog.at_level(logging.DEBUG, logger=encryption_module.__name__):
        EncryptionProvider(key=CONFIGURED_RAW_KEY)

    errors = [r for r in caplog.records if r.levelno >= logging.ERROR]
    assert (
        not errors
    ), f"Configured provider signalled: {[r.getMessage() for r in errors]}"


@pytest.mark.regression
def test_the_docstring_no_longer_advertises_silent_generation():
    """AC of #2092: the docstring stopped presenting generation as ordinary.

    It read ``key: 32-byte encryption key (if None, generates random key)``,
    which described a data-destroying default as a convenience.

    Falsifying result: that phrasing is still present.
    """
    doc = EncryptionProvider.__init__.__doc__ or ""
    assert "generates random key" not in doc, (
        "The docstring still advertises silent key generation as ordinary "
        "behaviour without its durability consequence."
    )


@pytest.mark.regression
def test_from_password_documents_that_the_salt_must_be_persisted():
    """``from_password`` mints a random salt that ``encrypt`` does NOT store.

    A caller who does not separately persist ``get_salt()`` cannot re-derive the
    key — the same unrecoverability outcome by a different mechanism. The
    behaviour is retained (changing the ciphertext envelope would break existing
    data), so the obligation must at least be stated.

    Falsifying result: the docstring never mentions persisting the salt.
    """
    doc = EncryptionProvider.from_password.__doc__ or ""
    assert (
        "get_salt" in doc and "persist" in doc.lower()
    ), "from_password must document that the caller has to persist the salt."


# ---------------------------------------------------------------------------
# The key-material FLOOR.
#
# These exist because the guards below had NO test at all when the floor first
# landed: deleting both `MIN_PASSPHRASE_LENGTH` checks left every other test in
# this file green. A green suite that stays green with the guard deleted is not
# evidence the guard works -- it is evidence the suite never asserted it. Every
# other constant in this module sits comfortably above the floor (39, 44, 32),
# so nothing here exercised the boundary by accident.
# ---------------------------------------------------------------------------


@pytest.mark.regression
@pytest.mark.parametrize("blank", ["", "   ", "\t\n ", "\n"])
def test_empty_or_whitespace_key_counts_as_unconfigured_not_as_a_passphrase(blank):
    """The worst case in this whole change: a FIXED key that looks configured.

    ``EncryptionProvider(key=os.environ.get("K", ""))`` is the ordinary way a
    caller spells "unset". Stretching ``""`` derives a key that is stable across
    every deployment on earth and reproducible by anyone reading this module's
    constants -- strictly worse than the per-process key this fix removes,
    because it looks configured and survives a restart.

    The refusal must be the NOT-CONFIGURED one, not the length one: a blank
    value is absent input, not a short passphrase, and the message has to point
    the operator at the wiring rather than at a character count.

    Falsifying result: construction succeeds, or raises the floor error.
    """
    with pytest.raises(EncryptionKeyNotConfiguredError) as exc_info:
        EncryptionProvider(key=blank)

    message = str(exc_info.value)
    assert "KAIZEN_ENCRYPTION_KEY" in message, (
        "A blank key must be reported as missing configuration and name the "
        "variable that supplies it."
    )
    assert "non-whitespace characters" not in message, (
        "A blank value is absent input, not a short passphrase; reporting a "
        "character count sends the operator to pad it rather than set it."
    )


@pytest.mark.regression
@pytest.mark.parametrize("passphrase", ["x", "short", "a" * 31])
def test_a_passphrase_below_the_floor_is_refused(passphrase):
    """600k PBKDF2 iterations do not rescue a brief passphrase.

    Falsifying result: construction succeeds, which is what happened before the
    floor existed -- ``EncryptionProvider(key="x")`` returned a working provider.
    """
    with pytest.raises(EncryptionKeyNotConfiguredError) as exc_info:
        EncryptionProvider(key=passphrase)

    message = str(exc_info.value)
    assert str(MIN_PASSPHRASE_LENGTH) in message, "the floor must be named"
    assert passphrase not in message, (
        "the refusal must name the length, never the passphrase itself -- this "
        "message reaches logs and crash reports"
    )


@pytest.mark.regression
def test_a_passphrase_exactly_at_the_floor_is_accepted():
    """The boundary is inclusive; the other polarity of the test above.

    Without this, tightening the comparison to ``<=`` would pass unnoticed.
    """
    provider = EncryptionProvider(key="a" * MIN_PASSPHRASE_LENGTH)
    assert len(provider.key) == 32


@pytest.mark.regression
@pytest.mark.parametrize("raw", [b"", b"too-short", b"a" * 31, b"a" * 33])
def test_raw_key_material_of_the_wrong_length_is_refused(raw):
    """AES-256 needs exactly 32 bytes; anything else is a caller error.

    ``b""`` is included deliberately: it is falsy, so an implementation that
    tests truthiness rather than type would route it to the not-configured
    branch and, under ``allow_ephemeral_key=True``, silently generate instead.

    Falsifying result: construction succeeds with wrong-sized material.
    """
    with pytest.raises(EncryptionKeyNotConfiguredError):
        EncryptionProvider(key=raw)


@pytest.mark.regression
def test_whitespace_is_significant_in_the_passphrase_itself():
    """Measured stripped, derived VERBATIM.

    Trimming would silently change the derived key for anyone whose passphrase
    ends in whitespace -- and a key that changes under the same configured value
    is the exact failure #2092 is about, one layer down.

    Falsifying result: the two keys are equal, meaning the value was trimmed
    before derivation.
    """
    bare = EncryptionProvider(key=CONFIGURED_PASSPHRASE)
    padded = EncryptionProvider(key=CONFIGURED_PASSPHRASE + " ")
    assert bare.key != padded.key, (
        "trailing whitespace was stripped before derivation, so a stray newline "
        "in a config file would silently change the key"
    )


@pytest.mark.regression
@pytest.mark.parametrize("password", ["", "   ", "x", "a" * 31])
def test_from_password_cannot_be_used_to_route_around_the_floor(password):
    """A floor a caller sidesteps by switching constructors is not a floor.

    ``from_password`` derives its own 32 bytes and hands them to the constructor,
    which accepts any correctly-sized raw key -- so before this check
    ``EncryptionProvider.from_password("x")`` succeeded on the same public class
    whose sibling constructor refuses 31 characters.

    Falsifying result: a provider is returned.
    """
    with pytest.raises(EncryptionKeyNotConfiguredError):
        EncryptionProvider.from_password(password)


@pytest.mark.regression
def test_from_password_still_works_at_and_above_the_floor():
    """The other polarity: the legitimate password-derivation path is intact."""
    provider = EncryptionProvider.from_password("p" * MIN_PASSPHRASE_LENGTH)
    round_tripped = provider.decrypt(provider.encrypt("sensitive"))
    assert round_tripped == "sensitive"


@pytest.mark.regression
def test_the_wrappers_enforce_the_floor_too(monkeypatch):
    """``KeyManager`` and ``FieldEncryptor`` route through the same chokepoint.

    Wrapper propagation is what hid #2092 in the first place -- a class that
    reads as fully configured forwarding an unconfigured default inward. The
    floor has to survive the same trip.

    Falsifying result: either wrapper accepts a sub-floor passphrase.
    """
    monkeypatch.delenv("KAIZEN_ENCRYPTION_KEY", raising=False)
    with pytest.raises(EncryptionKeyNotConfiguredError):
        KeyManager(key="tooshort")
    with pytest.raises(EncryptionKeyNotConfiguredError):
        FieldEncryptor(sensitive_fields=["ssn"], key="tooshort")


@pytest.mark.regression
@pytest.mark.parametrize("blank", ["", "   "])
def test_a_blank_environment_variable_does_not_configure_anything(monkeypatch, blank):
    """An exported-but-empty variable is the shape a shell script produces.

    ``export KAIZEN_ENCRYPTION_KEY=$SOMETHING_UNSET`` yields exactly this, and it
    must not read as configuration.

    Falsifying result: construction succeeds, meaning the blank export was
    stretched into a fixed, globally-reproducible key.
    """
    monkeypatch.setenv("KAIZEN_ENCRYPTION_KEY", blank)
    with pytest.raises(EncryptionKeyNotConfiguredError):
        EncryptionProvider()


# ---------------------------------------------------------------------------
# The SECOND consumer of KAIZEN_ENCRYPTION_KEY.
#
# ``CheckpointEncryptor`` reads the SAME environment variable through its
# ``key_env_var`` default and stretches it with the same PBKDF2-HMAC-SHA256 at
# the same iteration count. Before this, one variable with one documented floor
# produced two opposite outcomes: a four-character value got a hard refusal from
# ``EncryptionProvider`` and silent acceptance here (`security.md`
# § Enforcement-Surface Parity).
#
# The two modules use DIFFERENT PBKDF2 salts, deliberately -- non-interoperability
# between checkpoint storage and field encryption is the point, and these tests
# assert nothing about salt equality. Only the FLOOR is shared.
# ---------------------------------------------------------------------------


@pytest.mark.regression
@pytest.mark.parametrize("passphrase", ["x", "short", "a" * 31])
def test_checkpoint_encryptor_enforces_the_same_floor(passphrase):
    """The sibling consumer of the same variable refuses the same passphrase.

    Falsifying result: construction succeeds, which is what happened before --
    the identical value that ``EncryptionProvider`` refuses was accepted here.
    """
    from kaizen.core.autonomy.security.encryption import (
        CheckpointEncryptor,
        EncryptionError,
    )

    with pytest.raises(EncryptionError) as exc_info:
        CheckpointEncryptor(encryption_key=passphrase)

    message = str(exc_info.value)
    assert str(MIN_PASSPHRASE_LENGTH) in message, "the floor must be named"
    assert passphrase not in message, (
        "the refusal must name the length, never the passphrase itself -- this "
        "message reaches logs and crash reports"
    )


@pytest.mark.regression
def test_checkpoint_encryptor_accepts_a_passphrase_at_the_floor():
    """The other polarity: the legitimate path is intact and still derives a key.

    Without this, tightening the comparison to ``<=`` would pass unnoticed.
    """
    from kaizen.core.autonomy.security.encryption import CheckpointEncryptor

    encryptor = CheckpointEncryptor(encryption_key="a" * MIN_PASSPHRASE_LENGTH)
    assert len(encryptor.key) == 32


@pytest.mark.regression
@pytest.mark.parametrize("blank", ["", "   ", "\t\n "])
def test_checkpoint_encryptor_treats_blank_as_unset_not_as_a_passphrase(blank):
    """A blank value is absent input, not a short passphrase.

    Both spellings reach here: an explicit ``encryption_key=""`` and a blank
    export. The refusal must point at the wiring rather than at a character
    count, or the operator pads the value instead of setting it.

    Falsifying result: construction succeeds, or the message reports a length.
    """
    from kaizen.core.autonomy.security.encryption import (
        CheckpointEncryptor,
        EncryptionError,
    )

    with pytest.raises(EncryptionError) as exc_info:
        CheckpointEncryptor(encryption_key=blank)

    message = str(exc_info.value)
    assert "KAIZEN_ENCRYPTION_KEY" in message, (
        "a blank value must be reported as missing configuration and name the "
        "variable that supplies it"
    )
    assert "non-whitespace characters" not in message, (
        "a blank value is absent input, not a short passphrase; reporting a "
        "character count sends the operator to pad it rather than set it"
    )


@pytest.mark.regression
@pytest.mark.parametrize("blank", ["", "   "])
def test_checkpoint_encryptor_ignores_a_blank_environment_export(monkeypatch, blank):
    """``export KAIZEN_ENCRYPTION_KEY=$SOMETHING_UNSET`` on the sibling path."""
    from kaizen.core.autonomy.security.encryption import (
        CheckpointEncryptor,
        EncryptionError,
    )

    monkeypatch.setenv("KAIZEN_ENCRYPTION_KEY", blank)
    with pytest.raises(EncryptionError):
        CheckpointEncryptor()


@pytest.mark.regression
def test_checkpoint_encryptor_keeps_whitespace_significant_in_the_passphrase():
    """Measured stripped, derived VERBATIM -- the sibling's rule, here too.

    Falsifying result: the two keys are equal, meaning the value was trimmed
    before derivation and a stray newline in a config file would silently change
    the key.
    """
    from kaizen.core.autonomy.security.encryption import CheckpointEncryptor

    bare = CheckpointEncryptor(encryption_key=CONFIGURED_PASSPHRASE)
    padded = CheckpointEncryptor(encryption_key=CONFIGURED_PASSPHRASE + " ")
    assert bare.key != padded.key
