# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/contrib/ai_registry.py
#   IMPORT INSTEAD:      from kailash_mcp.contrib.ai_registry import ...
#
# NOTE: `ai_registry_server.py` was moved into the `contrib/`
# subpackage in the canonical codebase, which groups integrations
# with other Kailash frameworks.
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │   STOP. Do NOT edit this file.                                   │
# │   Canonical:                                                     │
# │     packages/kailash-mcp/src/kailash_mcp/contrib/ai_registry.py  │
# │   Edits to this shim will be LOST.                               │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.contrib.ai_registry import AIRegistryServer
#
# NOTE: A previous FastMCP-based variant at
#   src/kailash/mcp_server/servers/ai_registry.py
# was removed in SPEC-01 consolidation (0 consumers found in the
# repository). If you were using it, recover from
# scrap/pre-triage-snapshot-2026-04-08.
#
# Implementation: sys.modules identity swap for mock.patch compatibility.
# Tracking: src/kailash/mcp_server/DEPRECATED.md, SPEC-01
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM -- canonical at :mod:`kailash_mcp.contrib.ai_registry`."""

from __future__ import annotations

import sys as _sys
import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.ai_registry_server is deprecated; use "
    "`kailash_mcp.contrib.ai_registry`. See "
    "src/kailash/mcp_server/DEPRECATED.md.",
    DeprecationWarning,
    stacklevel=2,
)

import kailash_mcp.contrib.ai_registry as _canonical  # noqa: E402

_sys.modules[__name__] = _canonical
