# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/auth/providers.py
#   IMPORT INSTEAD:      from kailash_mcp.auth.providers import ...
#
# NOTE: the old flat file `auth.py` was restructured into a subpackage
# (`auth/`) in the canonical codebase. This shim maps the old flat-module
# import path to the new subpackage-based path.
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │   STOP. Do NOT edit this file.                                   │
# │   Canonical: packages/kailash-mcp/src/kailash_mcp/auth/providers.py│
# │   Edits to this shim will be LOST.                               │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.auth.providers import APIKeyAuth, JWTAuth, ...
#
# Implementation: sys.modules identity swap for mock.patch compatibility.
# Tracking: src/kailash/mcp_server/DEPRECATED.md, SPEC-01
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM -- canonical at :mod:`kailash_mcp.auth.providers`."""

from __future__ import annotations

import sys as _sys
import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.auth is deprecated; use "
    "`kailash_mcp.auth.providers`. See "
    "src/kailash/mcp_server/DEPRECATED.md.",
    DeprecationWarning,
    stacklevel=2,
)

import kailash_mcp.auth.providers as _canonical  # noqa: E402

_sys.modules[__name__] = _canonical
