# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/client.py
#   IMPORT INSTEAD:      from kailash_mcp.client import ...
#                    or  from kailash_mcp import MCPClient
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │                                                                  │
# │   STOP. Do NOT edit this file.                                   │
# │                                                                  │
# │   Canonical source:                                              │
# │     packages/kailash-mcp/src/kailash_mcp/client.py               │
# │                                                                  │
# │   Navigate there and make your changes in the canonical file.   │
# │   Edits to this shim will be LOST and will NOT reach consumers. │
# │                                                                  │
# │   When adding new exports, add them to the canonical package    │
# │   first, then regenerate this shim. See SPEC-01.                │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.client import MCPClient
#   or
#     from kailash_mcp import MCPClient
#
# Implementation note: this shim uses a sys.modules-level identity swap
# rather than a wildcard re-export. That way `mock.patch` on either the
# old or the new import path targets the SAME module object, preserving
# test compatibility for code that patches `kailash.mcp_server.client.X`.
#
# Tracking:
#   - src/kailash/mcp_server/DEPRECATED.md (migration guide)
#   - SPEC-01 (kailash-mcp package consolidation)
#   - kailash-rs parallel: crates/kailash-mcp/src/client.rs
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM -- canonical source at :mod:`kailash_mcp.client`.

All edits must happen in the canonical package; see the banner above.
"""

from __future__ import annotations

import sys as _sys
import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.client is deprecated and will be removed in a "
    "future release. Import from `kailash_mcp.client` instead. See "
    "src/kailash/mcp_server/DEPRECATED.md for the migration guide.",
    DeprecationWarning,
    stacklevel=2,
)

import kailash_mcp.client as _canonical  # noqa: E402

_sys.modules[__name__] = _canonical
