# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/discovery/discovery.py
#   IMPORT INSTEAD:      from kailash_mcp.discovery.discovery import ...
#
# NOTE: the flat file `discovery.py` was moved into a `discovery/`
# subpackage in the canonical codebase (alongside registry_integration.py).
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │   STOP. Do NOT edit this file.                                   │
# │   Canonical:                                                     │
# │     packages/kailash-mcp/src/kailash_mcp/discovery/discovery.py  │
# │   Edits to this shim will be LOST.                               │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.discovery.discovery import ...
#
# Implementation note: this shim uses a sys.modules-level identity swap
# rather than a wildcard re-export. That way `mock.patch` on either the
# old or the new import path targets the SAME module object, so existing
# tests that patch `kailash.mcp_server.discovery.logger` continue to
# work without modification. A wildcard `from X import *` approach
# cannot preserve this identity.
#
# Tracking: src/kailash/mcp_server/DEPRECATED.md, SPEC-01
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM -- canonical at :mod:`kailash_mcp.discovery.discovery`.

All edits must happen in the canonical package; see the banner above.
"""

from __future__ import annotations

import sys as _sys
import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.discovery is deprecated; use "
    "`kailash_mcp.discovery.discovery`. See "
    "src/kailash/mcp_server/DEPRECATED.md.",
    DeprecationWarning,
    stacklevel=2,
)

# Import the canonical module, then splice it into sys.modules under
# this shim's name. After this statement, `kailash.mcp_server.discovery`
# and `kailash_mcp.discovery.discovery` refer to the IDENTICAL module
# object. mock.patch on either path targets the same attribute binding,
# so existing tests continue to work.
import kailash_mcp.discovery.discovery as _canonical  # noqa: E402

_sys.modules[__name__] = _canonical
