# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/protocol/protocol.py
#   IMPORT INSTEAD:      from kailash_mcp.protocol.protocol import ...
#
# NOTE: `protocol.py` was moved into a `protocol/` subpackage alongside
# `jsonrpc.py`, `types.py`, and `errors.py`. The flat-module import path
# is preserved here as a shim.
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │   STOP. Do NOT edit this file.                                   │
# │   Canonical:                                                     │
# │     packages/kailash-mcp/src/kailash_mcp/protocol/protocol.py    │
# │   Edits to this shim will be LOST.                               │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.protocol.protocol import ProtocolManager, ...
#
# Implementation: sys.modules identity swap for mock.patch compatibility.
# Tracking: src/kailash/mcp_server/DEPRECATED.md, SPEC-01
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM -- canonical at :mod:`kailash_mcp.protocol.protocol`."""

from __future__ import annotations

import sys as _sys
import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.protocol is deprecated; use "
    "`kailash_mcp.protocol.protocol`. See "
    "src/kailash/mcp_server/DEPRECATED.md.",
    DeprecationWarning,
    stacklevel=2,
)

import kailash_mcp.protocol.protocol as _canonical  # noqa: E402

_sys.modules[__name__] = _canonical
