# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/discovery/registry_integration.py
#   IMPORT INSTEAD:      from kailash_mcp.discovery.registry_integration import ...
#
# NOTE: `registry_integration.py` was moved into the `discovery/`
# subpackage alongside `discovery.py` in the canonical codebase.
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │   STOP. Do NOT edit this file.                                   │
# │   Canonical:                                                     │
# │     packages/kailash-mcp/src/kailash_mcp/discovery/registry_integration.py│
# │   Edits to this shim will be LOST.                               │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.discovery.registry_integration import ServerRegistrar, ...
#
# Implementation: sys.modules identity swap for mock.patch compatibility.
# Tracking: src/kailash/mcp_server/DEPRECATED.md, SPEC-01
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM -- canonical at :mod:`kailash_mcp.discovery.registry_integration`."""

from __future__ import annotations

import sys as _sys
import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.registry_integration is deprecated; use "
    "`kailash_mcp.discovery.registry_integration`. See "
    "src/kailash/mcp_server/DEPRECATED.md.",
    DeprecationWarning,
    stacklevel=2,
)

import kailash_mcp.discovery.registry_integration as _canonical  # noqa: E402

_sys.modules[__name__] = _canonical
