# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/advanced/resource_cache.py
#   IMPORT INSTEAD:      from kailash_mcp.advanced.resource_cache import ...
#
# NOTE: `resource_cache.py` was moved into the `advanced/` subpackage
# in the canonical codebase.
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │   STOP. Do NOT edit this file.                                   │
# │   Canonical:                                                     │
# │     packages/kailash-mcp/src/kailash_mcp/advanced/resource_cache.py│
# │   Edits to this shim will be LOST.                               │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.advanced.resource_cache import ...
#
# Implementation: sys.modules identity swap for mock.patch compatibility.
# Tracking: src/kailash/mcp_server/DEPRECATED.md, SPEC-01
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM -- canonical at :mod:`kailash_mcp.advanced.resource_cache`."""

from __future__ import annotations

import sys as _sys
import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.resource_cache is deprecated; use "
    "`kailash_mcp.advanced.resource_cache`. See "
    "src/kailash/mcp_server/DEPRECATED.md.",
    DeprecationWarning,
    stacklevel=2,
)

import kailash_mcp.advanced.resource_cache as _canonical  # noqa: E402

_sys.modules[__name__] = _canonical
