# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/server.py
#   IMPORT INSTEAD:      from kailash_mcp.server import ...
#                    or  from kailash_mcp import MCPServer, MCPServerBase
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │   STOP. Do NOT edit this file.                                   │
# │   Canonical: packages/kailash-mcp/src/kailash_mcp/server.py      │
# │   Edits to this shim will be LOST.                               │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.server import MCPServer, MCPServerBase
#
# Implementation: sys.modules identity swap — see discovery.py for the
# pattern rationale (preserves mock.patch compatibility).
#
# Tracking: src/kailash/mcp_server/DEPRECATED.md, SPEC-01
# kailash-rs parallel: crates/kailash-mcp/src/server/
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM -- canonical source at :mod:`kailash_mcp.server`."""

from __future__ import annotations

import sys as _sys
import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.server is deprecated; use `kailash_mcp.server` "
    "instead. See src/kailash/mcp_server/DEPRECATED.md.",
    DeprecationWarning,
    stacklevel=2,
)

import kailash_mcp.server as _canonical  # noqa: E402

_sys.modules[__name__] = _canonical
