# ══════════════════════════════════════════════════════════════════════
# ⚠️  DEPRECATED SHIM — DO NOT EDIT THIS FILE
# ══════════════════════════════════════════════════════════════════════
#
#   CANONICAL LOCATION:  packages/kailash-mcp/src/kailash_mcp/transports/transports.py
#   IMPORT INSTEAD:      from kailash_mcp.transports.transports import ...
#
# NOTE: `transports.py` was moved into the `transports/` subpackage
# in the canonical codebase to make room for per-transport modules.
#
# ┌──────────────────────────────────────────────────────────────────┐
# │ 🤖 IF YOU ARE AN AI CODING AGENT READING THIS FILE:              │
# │   STOP. Do NOT edit this file.                                   │
# │   Canonical:                                                     │
# │     packages/kailash-mcp/src/kailash_mcp/transports/transports.py│
# │   Edits to this shim will be LOST.                               │
# └──────────────────────────────────────────────────────────────────┘
#
# HUMAN DEVELOPER: update imports to
#     from kailash_mcp.transports.transports import ...
#
# Implementation: sys.modules identity swap for mock.patch compatibility.
# Tracking: src/kailash/mcp_server/DEPRECATED.md, SPEC-01
# kailash-rs parallel: crates/kailash-mcp/src/transport/ with
#   stdio.rs, http.rs, sse.rs, in_memory.rs as peer modules.
# ══════════════════════════════════════════════════════════════════════
"""DEPRECATED SHIM -- canonical at :mod:`kailash_mcp.transports.transports`."""

from __future__ import annotations

import sys as _sys
import warnings as _warnings

_warnings.warn(
    "kailash.mcp_server.transports is deprecated; use "
    "`kailash_mcp.transports.transports`. See "
    "src/kailash/mcp_server/DEPRECATED.md.",
    DeprecationWarning,
    stacklevel=2,
)

import kailash_mcp.transports.transports as _canonical  # noqa: E402

_sys.modules[__name__] = _canonical
