"""
Example script demonstrating how to use the HMI workflow.

This script initializes and runs the HMI workflow for handling patient
specialist referrals, showcasing the switch-based conditional routing
and asynchronous execution.
"""

import asyncio
import logging
from typing import Any, Dict, List

from examples.migrations.project_hmi.adapted.workflow import (
    HmiWorkflow,
    create_initial_state,
)

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Simple LLM implementation for demonstration
class SimpleLLM:
    """
    A simple mock LLM for demonstration purposes.

    In a real-world scenario, this would be replaced with a connection
    to an actual language model service.
    """

    async def ainvoke(self, messages: List[Dict[str, Any]]) -> Dict[str, str]:
        """
        Simulate an async LLM call.

        Args:
            messages: The input messages

        Returns:
            Dict with content field containing the generated text
        """
        # Simulate some processing time
        await asyncio.sleep(0.5)

        # Check the messages and generate a response
        system_content = (
            messages[0].get("content", "")
            if messages and messages[0].get("role") == "system"
            else ""
        )
        user_content = (
            messages[1].get("content", "")
            if len(messages) > 1 and messages[1].get("role") == "user"
            else ""
        )

        # Simple template filling simulation
        if "fill" in system_content.lower() and "template" in system_content.lower():
            # Extract some data from the user content (which should be JSON)
            import json

            try:
                data = json.loads(user_content)
                template = data.get("template_string_to_fill", "")
                patient_data = data.get("patient_details_data", {})
                doctor_data = data.get("doctor_profile_data", {})
                slot_data = data.get("earliest_slot_data", {})

                # Very basic template replacement
                template = template.replace(
                    "{patient_details.patient_name}",
                    patient_data.get("patient_name", "Patient"),
                )
                template = template.replace(
                    "{doctor_profile.name}", doctor_data.get("name", "Doctor")
                )
                template = template.replace(
                    "{doctor_profile.specialty}",
                    doctor_data.get("specialty", "Specialist"),
                )

                # Handle photo URL
                if doctor_data.get("photoUrl"):
                    template = template.replace(
                        "{doctor_profile.photoUrl}",
                        f"Photo: {doctor_data.get('photoUrl')}",
                    )
                else:
                    # Remove the whole photo line
                    template = template.replace("Photo: {doctor_profile.photoUrl}", "")

                template = template.replace(
                    "{earliest_slot.appointmentStartTime}",
                    slot_data.get("appointmentStartTime", "soon"),
                )
                template = template.replace(
                    "{earliest_slot.location}", slot_data.get("location", "the clinic")
                )

                return {"content": template}
            except Exception as e:
                logger.error(f"Error in template filling: {e}")
                return {"content": "I couldn't process the template correctly."}

        # Default response
        return {"content": "Hello! This is a response from the simple LLM."}


async def main():
    """Run the HMI workflow example."""
    # Create the LLM instance
    llm = SimpleLLM()

    # Create the workflow
    workflow = HmiWorkflow(llm=llm)

    # Create the initial state
    state = create_initial_state()

    # Execute the workflow
    logger.info("Starting workflow execution")
    try:
        updated_state = await workflow.execute_workflow1(state)

        # Check the result
        if updated_state.next_message_to_patient:
            logger.info(
                f"Workflow generated message: {updated_state.next_message_to_patient}"
            )
        else:
            logger.warning("No message generated by the workflow")

        # Additional state inspection
        if updated_state.w1_context.no_hmi_slot_flag:
            logger.info("No HMI slot was found")
        else:
            logger.info("Found an HMI slot")

        if updated_state.w1_context.current_doctor_under_consideration:
            doctor = updated_state.w1_context.current_doctor_under_consideration
            logger.info(
                f"Selected doctor: {doctor.doctor_name} ({doctor.doctor_specialties})"
            )

    except Exception as e:
        logger.error(f"Error executing workflow: {e}")
        raise


if __name__ == "__main__":
    asyncio.run(main())
