#!/usr/bin/env node
/*
 * MCP Guardrail Companion Server — Codex fallback for hooks/*.js
 *
 * Emitted to `.codex-mcp-guard/server.js` in USE templates when
 * `codex_hooks.feature_flag = under_development` (see sync-manifest.yaml
 * cli_variants.hooks/*.js.codex.feature_flag_fallback).
 *
 * Contract: every reject-condition implemented in .claude/hooks/*.js MUST
 * have a coverage-equivalent reject-condition in this server. Enforced by
 * /sync emit-time validator 13 (AST predicate-set match) — see v5 spec.
 *
 * Module system: CommonJS (matches .claude/hooks/*.js convention).
 *
 * Architecture
 * ────────────
 * 1. POLICIES populated from sibling policies.json at import time.
 *    Generated by `extract-policies.mjs --write-policies` and refreshed
 *    on every /sync. Each per-tool array entry is `{ source_file,
 *    cc_matchers, invocation: "subprocess" }` — server.js spawns
 *    `node ../hooks/<source_file>` for every entry on the matching
 *    Codex tool call.
 *
 * 2. POLICIES_POPULATED flips true iff at least one wrapped Codex tool
 *    has ≥1 policy entry. Empty policies.json or absent file ⇒ stays
 *    false; the gate at the bottom of this file then exits 2 with the
 *    refusal message rather than running the server fail-open.
 *
 * 3. On MCP tool invocation:
 *    - Synthesize a CC-shaped PreToolUse JSON payload from the MCP args
 *      ({ tool_name, tool_input, hook_event_name, cwd, session_id }).
 *    - For each policy entry, spawn the hook script as a subprocess
 *      (5s timeout per cc-artifacts.md Rule 7), pipe payload to stdin,
 *      capture stdout + exit code.
 *    - Exit 0 ⇒ allow; exit 2 ⇒ deny with hook stdout's instructAndWait
 *      shape translated to MCP isError; other exits ⇒ allow + log to
 *      violations.jsonl (per zero-tolerance.md Rule 2).
 *    - Every policy entry MUST allow for the call to forward.
 */

"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
const HERE = __dirname;

// Layout detection: this server runs in two distinct emission shapes.
//
//   1. loom-dev layout                        — HERE = <repo>/.claude/codex-mcp-guard/
//      hooks at HERE/../hooks                 → COC_ROOT = HERE/..
//
//   2. multi-CLI USE-template / coc-project   — HERE = <repo>/.codex-mcp-guard/
//      hooks at HERE/../.claude/hooks         → COC_ROOT = HERE/../.claude
//
// loom-dev and multi-CLI USE templates additionally place a symlink
// `<root>/.claude/codex-mcp-guard → ../.codex-mcp-guard` (per
// sync-manifest.yaml::multi_cli_overlays.<type>.symlinks); node resolves
// __dirname via fs.realpath so HERE always points to the real directory,
// not the symlink. Both layouts converge on COC_ROOT = `<root>/.claude/`.
function resolveCocRoot(here) {
  const loomDev = path.resolve(here, "..");
  if (fs.existsSync(path.join(loomDev, "hooks"))) return loomDev;
  const useTemplate = path.resolve(here, "..", ".claude");
  if (fs.existsSync(path.join(useTemplate, "hooks"))) return useTemplate;
  // Neither layout matches — fall back so HOOKS_DIR still points
  // somewhere; the startup existence check (logged via self-check
  // diagnostics, line ~305) will surface the failure loudly.
  return loomDev;
}
const COC_ROOT = resolveCocRoot(HERE);
const HOOKS_DIR = path.join(COC_ROOT, "hooks");
const POLICIES_PATH = path.join(HERE, "policies.json");
const VIOLATIONS_PATH = path.join(COC_ROOT, "learning", "violations.jsonl");
const SUBPROCESS_TIMEOUT_MS = 5000; // cc-artifacts.md Rule 7

// #820: the runtime label this guard runs under, single-sourced so BOTH the
// replayed-hook subprocess env stamp (invokeHook) AND the re-emitted CC-contract
// output shape (ccHookSpecificOutput) carry the same value. A downstream reader of
// the guard's MCP verdict can attribute it to the Codex enforcement lane, and any
// replayed hook adopting lib/runtime.js::parseHook (which THROWS on unset
// COC_RUNTIME) fails closed, not open, under the guard's replay. The guard replays
// CC hooks in the Codex lane, so `codex` is the correct label.
const COC_RUNTIME = "codex";

// Tool-wrap scope (parity with cli_variants.hooks/*.js.codex.wraps).
// Read-path tools (read, grep_tool, glob_tool) are INTENTIONALLY out of
// scope in the MCP fallback path — hooks with read-only policies are
// skipped on Codex when codex_hooks=under_development. Documented in
// README.md § Scope.
const WRAPPED_TOOLS = Object.freeze(["apply_patch", "unified_exec", "shell"]);

// Codex tool → canonical CC tool name. The CC PreToolUse hooks classify by CC
// tool name: posture-gate / signing-mutation-guard / operator-gate route through
// `isMutationTool(tool)` / `tool === "Bash"`. This guard REPLAYS those hooks
// against Codex tool calls, so the synthesized PreToolUse payload MUST present
// the CC-native tool name — otherwise the hook's tool-name classification no-ops
// and the gate is registered-but-INERT (FF-AC6-1 walk finding). Translating here
// also fires the latent DF-AC6-2 shell-lane gap, where posture/signing/operator
// gates keyed on `tool === "Bash"` never fired against `tool_name: "shell"` (only
// the command-string-based validate-bash-command worked on that lane).
// NOTE: this map governs ONLY the policy-evaluation payload (evaluatePolicies);
// the provenance-capture path (synthesizeCaptureInput) deliberately keeps the raw
// Codex tool name for accurate provenance, and POLICIES[tool] stays keyed by the
// Codex tool name (policies.json is Codex-tool-keyed).
const CODEX_TO_CC_TOOL = Object.freeze({
  shell: "Bash",
  unified_exec: "Bash",
  apply_patch: "Edit",
});

// Upper bound on per-target gate fan-out for a single apply_patch call. A
// crafted patch with thousands of `*** Update File:` markers would otherwise
// spawn (policies × targets) serial subprocesses. Beyond the cap the overflow
// targets are NOT gated per-target; the call is forwarded with a surfaced
// halt-and-report advisory (fail-direction = surface, never silent-allow) +
// a `codex_mcp_guard_target_cap` breadcrumb (R2 security LOW-R2-2). Realistic
// Codex patches touch tens of files; 256 is well above that and below any
// spawn-storm threshold.
const MAX_GATE_TARGETS = 256;

// ---------------------------------------------------------------------------
// Provenance capture (loom#411 item 1 / #440)
// ---------------------------------------------------------------------------
// apply_patch is the ONE wrapped tool with no native Codex hook (codex#16732),
// so journal-DECISION + file-write Action capture on Codex rides THIS guard, not
// .codex/hooks.json. The capture hook is invoked as a NON-BLOCKING side-effect
// (it always exits 0); it is deliberately NOT a policies.json entry — registering
// it in the policy chain would make capture order-dependent and skippable on a
// sibling deny, breaking the deterministic intent-capture property (journal/0216
// intent-vs-execution residual). shell / unified_exec are NOT captured here —
// they capture via the native shell registration in .codex/hooks.json, so
// capturing them here too would double-record. The CAPTURE_* exports are the
// SSOT the F101-4 validator (validate-emit.mjs::checkProvenanceParity) reads to
// verify a `wired|<hook>@codex-mcp-guard` parity cell.
const CAPTURE_HOOK = "provenance-capture-tool.js";
const CAPTURE_HOOKS = Object.freeze([CAPTURE_HOOK]);
const CAPTURE_TOOLS = Object.freeze(["apply_patch"]);

// V4A apply_patch envelope target-path markers (Codex's documented patch format).
const V4A_FILE_RE = /^\*\*\*\s+(?:Update|Add|Delete) File:\s+(.+?)\s*$/;
const V4A_MOVE_RE = /^\*\*\*\s+Move to:\s+(.+?)\s*$/;

// Lazy + memoized: JOURNAL_DECISION_RE lives in the capture hook (SSOT). We only
// need it to PREFER a journal-DECISION target among a multi-file patch; if the
// hook is unreadable we fall back to the first target (Decision degrades to
// Action — captured, never fake).
let _journalDecisionRe; // undefined = not loaded; null = load failed
function journalDecisionRe() {
  if (_journalDecisionRe !== undefined) return _journalDecisionRe;
  try {
    _journalDecisionRe =
      require(path.join(HOOKS_DIR, CAPTURE_HOOK)).JOURNAL_DECISION_RE || null;
  } catch {
    _journalDecisionRe = null;
  }
  return _journalDecisionRe;
}

// ---------------------------------------------------------------------------
// Policy table — populated from sibling policies.json
// ---------------------------------------------------------------------------
function loadPolicies() {
  const empty = Object.fromEntries(WRAPPED_TOOLS.map((t) => [t, []]));
  if (!fs.existsSync(POLICIES_PATH)) return { policies: empty, source: null };
  try {
    const raw = JSON.parse(fs.readFileSync(POLICIES_PATH, "utf8"));
    const merged = Object.fromEntries(
      WRAPPED_TOOLS.map((t) => [
        t,
        Array.isArray(raw.policies?.[t]) ? raw.policies[t] : [],
      ]),
    );
    return { policies: merged, source: POLICIES_PATH };
  } catch (e) {
    process.stderr.write(
      `codex-mcp-guard: failed to parse ${POLICIES_PATH}: ${e.message}\n`,
    );
    return { policies: empty, source: null };
  }
}

const { policies: POLICIES, source: POLICIES_SOURCE } = loadPolicies();

// POLICIES_POPULATED true iff at least one wrapped tool has at least
// one policy entry. Per zero-tolerance.md Rule 2 (no stubs), an empty
// table is indistinguishable from no enforcement and MUST keep the
// fail-closed gate engaged. Note: this is a derived runtime flag, NOT
// a hand-edited constant — it reflects the actual state of POLICIES.
const POLICIES_POPULATED = WRAPPED_TOOLS.some(
  (t) => Array.isArray(POLICIES[t]) && POLICIES[t].length > 0,
);

// ---------------------------------------------------------------------------
// Violations log helper — writes to .claude/learning/violations.jsonl
// when a policy enforcement decision is non-trivial (subprocess
// timeout, parse error, deny, surface). Best-effort: hooks own the canonical
// violation log; this is supplementary breadcrumbs from the MCP path.
//
// MUST-6 exemption (knowledge-convergence.md): these MCP-side breadcrumbs are
// INTENTIONALLY NOT routed through appendStamped(). The guard is the Codex
// fallback emitted to a USE-template/coc-project `.codex-mcp-guard/` where the
// multi-operator signing substrate (coc-append.js + identity resolution) is the
// in-process HOOKS' domain, not the guard's — the guard runs as a standalone
// subprocess companion and deliberately avoids that dependency (it lazy-loads
// even the MCP SDK). The canonical SIGNED attribution log is owned by the
// in-process hooks via appendStamped; this best-effort breadcrumb is a
// supplementary MCP-path trace, not a posture-downgrade-counting record. The
// divergence is explicit here (not silent drift) so a future operator can elect
// to wire appendStamped if the guard ever runs inside the full substrate.
// ---------------------------------------------------------------------------
function logViolation(entry) {
  try {
    const dir = path.dirname(VIOLATIONS_PATH);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const line = JSON.stringify({ ts: new Date().toISOString(), ...entry });
    fs.appendFileSync(VIOLATIONS_PATH, line + "\n");
  } catch {
    // Failure to log is non-fatal; do not block tool execution.
  }
}

// ---------------------------------------------------------------------------
// Hook subprocess invocation — exact CC PreToolUse contract
// ---------------------------------------------------------------------------
// Exit code semantics per .claude/hooks/*.js convention:
//   0 = allow, 2 = block (deny). A clean non-zero non-2 exit splits (F-CGUARD-EXIT1):
//   `warn` (advisory-forward) IF stdout carried a parseable decision — the Rule-7
//   timeout-fallback advisory — else `crash` (fail-closed, a load-crash with no decision).
// Synthesizes the CC-shaped stdin payload from MCP args. Each policy entry is a
// separate process. A `warn` verdict (the hook RAN, returned a clean non-2 exit, AND
// emitted a parseable decision) is advisory-forward. But a hook that could NOT be
// evaluated — `timeout` (hung), `error` (spawn failure), `missing` (no source file for a
// gated tool), or `crash` (node launched it, it threw / failed to load, and it exited
// non-zero with NO parseable stdout decision) — FAILS CLOSED at evaluatePolicies (#411
// compliance-bus posture): the guard denies rather than silently forward. This guard is a
// security policy-ENFORCEMENT surface, NOT a session-continuation hook, so cc-artifacts.md
// Rule 7's session-hook fail-open (don't wedge the session on a buggy hook) does
// NOT apply to an un-evaluable enforcement verdict here.
function invokeHook({ hookFile, payload }) {
  const hookPath = path.join(HOOKS_DIR, hookFile);
  if (!fs.existsSync(hookPath)) {
    return {
      verdict: "missing",
      exitCode: -1,
      stdout: "",
      stderr: `hook script not found: ${hookPath}`,
    };
  }
  const r = spawnSync("node", [hookPath], {
    input: JSON.stringify(payload),
    encoding: "utf8",
    timeout: SUBPROCESS_TIMEOUT_MS,
    // #820: stamp COC_RUNTIME=codex into the replayed-hook subprocess env.
    // lib/runtime.js::parseHook validates COC_RUNTIME against the closed enum
    // {cc,codex,gemini} and THROWS when it is unset — so any hook adopting
    // parseHook would fail closed under the guard's replay. The guard replays CC
    // hooks in the Codex enforcement lane, so `codex` is the correct label.
    env: {
      ...process.env,
      CLAUDE_PROJECT_DIR: payload.cwd || process.cwd(),
      COC_RUNTIME,
    },
  });
  if (r.error && r.error.code === "ETIMEDOUT") {
    return {
      verdict: "timeout",
      exitCode: -2,
      stdout: r.stdout || "",
      stderr: r.stderr || "",
    };
  }
  if (r.error) {
    return {
      verdict: "error",
      exitCode: -3,
      stdout: r.stdout || "",
      stderr: String(r.error),
    };
  }
  const code = r.status === null ? -4 : r.status;
  const stdout = r.stdout || "";
  const { validation, continueFlag, permissionDecision } =
    extractHookValidation(stdout);
  let verdict;
  let surfaceValidation = null;
  if (code === 2 || continueFlag === false || permissionDecision === "deny") {
    // exit 2 (the PreToolUse block contract) OR an explicit continue:false
    // even at exit 0 OR the modern hookSpecificOutput.permissionDecision:"deny"
    // (#820 R1 LOW-1 — a pure-modern-shape deny at exit 0 with no `continue`).
    // A continue:false-with-exit-0 (or deny-at-exit-0) hook is contradictory;
    // the guard honors the MORE-RESTRICTIVE block intent defensively rather than
    // forwarding a tool the hook signaled to block. translateDeny re-parses
    // stdout for the message.
    verdict = "deny";
  } else if (permissionDecision === "ask") {
    // #820 follow-up (CGUARDask): the modern CC PreToolUse "ask" decision
    // (hookSpecificOutput.permissionDecision:"ask" at exit 0, no continue:false)
    // requests INTERACTIVE user confirmation before the tool proceeds. The Codex
    // enforcement lane has no interactive confirm channel at the guard, so "ask"
    // collapses to SURFACE — forward the tool BUT surface the reason — mirroring
    // CC's non-auto-approve → human-visible prompt. Silent ALLOW (the pre-fix
    // fall-through) drops the signal entirely: the Codex operator loses the
    // advisory a CC user would be prompted with (the #442 cross-CLI parity class,
    // #820 LOW-1's sibling on the "ask" verb). Hard-DENY would over-block — "ask"
    // is explicitly NOT "deny" (a deny is caught by the branch above). The reason
    // rides permissionDecisionReason, which extractHookValidation already folds
    // into `validation`; surface it even when it carries no
    // ACTIONABLE_VALIDATION_HEADS head (an ask reason is a free-form string, not a
    // canonical halt-and-report body, so isActionableValidation would gate it out).
    verdict = "surface";
    surfaceValidation =
      validation ||
      'Hook requested user confirmation (permissionDecision:"ask"); ' +
        "no interactive confirm on the Codex lane — tool forwarded, review before relying on it.";
  } else if (code === 0) {
    // Exit 0 is allow — BUT a HALT-AND-REPORT hook also exits 0 (it emits
    // { continue:true, hookSpecificOutput:{validation} } per
    // hook-output-discipline.md MUST-2; the lexical signal cannot carry block,
    // so the server-side GitHub rejection is the structural defense).
    // Distinguish the two by an ACTIONABLE validation head — NOT the mere
    // presence of a validation field. instruct-and-wait.js emits an
    // all-clear sentinel ("Validated" / "Not a deployment file") through the
    // SAME { continue:true, hookSpecificOutput:{validation} } shape, so keying
    // on presence alone would surface a spurious advisory on EVERY clean call.
    // Only a genuine halt-and-report/advisory body (carrying an instructAndWait
    // head) is "surface" (forward the tool BUT surface the message, mirroring
    // CC's continue:true + surfaced-message); everything else is plain "allow".
    if (isActionableValidation(validation)) {
      verdict = "surface";
      surfaceValidation = validation;
    } else {
      verdict = "allow";
    }
  } else {
    // Clean non-zero non-2 exit (most commonly exit 1). F-CGUARD-EXIT1 (journal/0535):
    // distinguish a DELIBERATE cc-artifacts.md Rule-7 timeout-fallback advisory (wrote a
    // parseable {continue:true} to stdout THEN exited 1 — 45 real hooks do this) from a
    // LOAD-CRASH (node launched the hook, it threw / failed to parse, exited non-zero
    // having written NO parseable decision to stdout). The advisory is advisory-forward
    // ("warn", byte-behavior-unchanged); the crash is UN-EVALUABLE on this enforcement
    // surface and MUST fail closed (deny) — the same #411 posture the timeout/error/missing
    // trio takes, matching the guard's own "crash fails closed" contract. extractHookValidation
    // cannot tell them apart (a bare {continue:true} returns all-nulls, like a crash), so the
    // discriminator keys on hasParseableHookDecision(stdout).
    verdict = hasParseableHookDecision(stdout) ? "warn" : "crash";
  }
  return {
    verdict,
    exitCode: code,
    stdout,
    stderr: r.stderr || "",
    validation: surfaceValidation,
  };
}

// ---------------------------------------------------------------------------
// Hook stdout → MCP isError translation
// ---------------------------------------------------------------------------
// CC hooks emit canonical instructAndWait JSON on stdout when blocking.
// Shape: { continue: false, hookSpecificOutput: { hookEventName,
// validation } } (PreToolUse) or { continue: true, systemMessage }
// (Stop-class). MCP requires { isError: true, content: [{ type: "text",
// text }] }. translateDeny extracts the human-readable validation text.
// Parse a hook's stdout for the canonical validation/continue shape. CC hooks
// emit one JSON line (occasionally multi-line on bad authoring); take the LAST
// non-empty line that parses to an object carrying a validation message.
// Shapes: { continue:false, hookSpecificOutput:{validation} } (deny, exit 2) OR
// { continue:true, hookSpecificOutput:{validation} } (HALT-AND-REPORT, exit 0,
// per hook-output-discipline.md MUST-2) OR { continue:true, systemMessage }
// (Stop-class). Returns { validation, continueFlag }; validation null when none.
// #71 restrictiveness ranking for a permissionDecision value across a multi-line
// hook stdout. A NON-allow decision on ANY line MUST survive (fail-closed): deny
// outranks ask outranks allow/absent/unrecognized. Unrecognized values rank 0 (NOT
// tightest) deliberately — invokeHook only ACTS on "deny"/"ask", and ranking an
// unknown string as deny would silently promote a typo'd decision to a block; the
// fail-closed direction here is "a recognized non-allow decision is never dropped",
// not "any unknown token blocks".
function rankPermissionDecision(pd) {
  if (pd === "deny") return 2;
  if (pd === "ask") return 1;
  return 0; // "allow" / absent / unrecognized
}

function extractHookValidation(hookStdout) {
  let validation = null;
  let continueFlag = null;
  let permissionDecision = null;
  try {
    const lines = (hookStdout || "")
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean);
    // #71: the permissionDecision + continue:false BLOCK signals are captured from
    // the FULL stdout, independently of the first-validation `break` below. The
    // prior single-`break` scan read permissionDecision only up to (and including)
    // the first validation-bearing line found scanning upward; a hook emitting
    // MULTI-LINE stdout whose validation object sits on a LATER line than a bare
    // `{"hookSpecificOutput":{"permissionDecision":"ask"}}` object had its "ask"
    // never read (the break fired at the validation line before the decision line
    // was reached), fell through to the code===0 branch, and — if the validation
    // was non-actionable — resolved to verdict "allow" with the advisory silently
    // dropped. NOT reachable from realistic single-line CC output (verified), so
    // this is hardening, not a live exploit. The single-line CC path is unchanged:
    // one JSON line carries validation + continue + permissionDecision together, so
    // all three are read from the same object exactly as before.
    let validationCaptured = false;
    for (let i = lines.length - 1; i >= 0; i--) {
      let obj;
      try {
        obj = JSON.parse(lines[i]);
      } catch {
        // not JSON; continue scanning upward
        continue;
      }
      // #71: capture the modern permissionDecision from EVERY line, most-restrictive
      // wins (deny > ask > allow/absent). A split-line ask/deny — the decision object
      // on a different line than the validation object — is therefore always read,
      // regardless of scan order, and a recognized non-allow decision can never be
      // overwritten by a weaker one on another line.
      const pd = obj?.hookSpecificOutput?.permissionDecision;
      if (
        pd &&
        (permissionDecision === null ||
          rankPermissionDecision(pd) >
            rankPermissionDecision(permissionDecision))
      ) {
        permissionDecision = pd;
      }
      // #71: a `continue:false` on ANY line is a block signal — honor it fail-closed,
      // not only from the validation-bearing line the single `break` used to stop at.
      if (obj?.continue === false) continueFlag = false;
      // #466 canonicalized the halting-hook output field from
      // `hookSpecificOutput.validation` to `hookSpecificOutput.additionalContext`
      // (the instruct-and-wait shape). Read BOTH so the surface-verdict still
      // fires post-#466 — otherwise an exit-0 halt-and-report hook resolves to
      // verdict "allow" and the Codex agent silently loses the advisory a CC
      // agent gets (#442 cross-CLI parity regression). The clean-call sentinel
      // ("Validated") still rides additionalContext too, but isActionableValidation
      // gates it out, so clean-call ZERO-warning parity is preserved.
      //
      // #820: a modern CC PreToolUse DENY emits
      // { hookSpecificOutput: { permissionDecision:"deny", permissionDecisionReason:"…" } }.
      // Read permissionDecisionReason (positioned after legacy `validation`, before
      // `additionalContext`) so translateDeny surfaces the actionable deny reason
      // instead of the generic "hook blocked the tool invocation" fallback. Safe on
      // the exit-0 allow/surface path: a deny reason does not begin with an
      // ACTIONABLE_VALIDATION_HEADS head, so isActionableValidation still gates it
      // out of the clean-call surface (no spurious advisory on a clean call).
      //
      // The validation body + its own `continue` come from the LAST validation-bearing
      // line ONLY (first found scanning upward) — the pre-#71 break semantics — so the
      // single-line CC path is byte-for-byte unchanged. A `continue:false` seen on any
      // OTHER line still forces continueFlag=false above (fail-closed), never
      // overwritten back to the validation line's `continue` here.
      if (!validationCaptured) {
        const v =
          obj?.hookSpecificOutput?.validation ||
          obj?.hookSpecificOutput?.permissionDecisionReason ||
          obj?.hookSpecificOutput?.additionalContext ||
          obj?.systemMessage ||
          null;
        if (v) {
          validation = v;
          if (continueFlag !== false) continueFlag = obj?.continue ?? null;
          validationCaptured = true;
        }
      }
    }
  } catch {
    /* parse failure — caller falls back */
  }
  return { validation, continueFlag, permissionDecision };
}

// Crash-vs-advisory discriminator for a clean non-zero-non-2 hook exit (F-CGUARD-EXIT1,
// journal/0535). A hook that DELIBERATELY exits non-zero as a cc-artifacts.md Rule-7
// timeout-fallback advisory FIRST writes a canonical decision to stdout
// (`{"continue":true}` — the shape 45 real hooks emit, e.g. posture-gate.js:44) and THEN
// exits 1. A hook that node LAUNCHED but that CRASHED (uncaught throw / syntax / load
// error) exits non-zero having written NO parseable decision to stdout (its stack trace
// goes to stderr). This predicate returns true iff stdout carries an intentional decision:
//   true  => honor as advisory-forward ("warn");
//   false => a load-crash the enforcement lane MUST fail closed on (same #411 posture as
//            the timeout/error/missing trio).
// NOTE: extractHookValidation alone cannot discriminate — a bare `{"continue":true}` (no
// validation body, `continue !== false`) returns all-nulls, identical to a crash that
// emitted nothing — hence this dedicated presence check over the recognized decision keys.
// The key-set is EXACTLY what the guard actually consumes downstream: `continue`
// (extractHookValidation continueFlag + the code===2/continue:false deny branch),
// `hookSpecificOutput` (permissionDecision deny/ask + validation/additionalContext), and
// `systemMessage` (Stop-class advisory). A hook's TOP-LEVEL `decision` field is NOT read
// anywhere in this guard, so it is deliberately EXCLUDED — recognizing a key the guard
// cannot act on would let a `{"decision":...}`-then-crash read as an advisory instead of
// failing closed (R1 security-reviewer, resolved by construction: fail-closed on any stdout
// carrying no guard-consumable decision).
function hasParseableHookDecision(hookStdout) {
  const lines = (hookStdout || "")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);
  for (const line of lines) {
    let obj;
    try {
      obj = JSON.parse(line);
    } catch {
      continue; // not JSON (e.g. a stack-trace line) — keep scanning
    }
    if (
      obj &&
      typeof obj === "object" &&
      ("continue" in obj ||
        "hookSpecificOutput" in obj ||
        "systemMessage" in obj)
    ) {
      return true;
    }
  }
  return false;
}

// instruct-and-wait.js::buildValidationBody emits an ACTIONABLE validation body
// beginning with exactly one of these canonical heads. An all-clear sentinel
// ("Validated" / "Not a deployment file") carries NO head — it flows through the
// same { continue:true, hookSpecificOutput:{validation} } legacy-advisory shape,
// so the head is the ONLY structural discriminator between a real halt-and-report
// and a clean confirmation. The guard surfaces ONLY actionable bodies so a clean
// Codex call is not spammed with a false advisory on every command. The block
// head ("STOP — Tool call blocked.") is exit-2 → the deny path, never surface;
// it is intentionally absent here. Coupling to instruct-and-wait.js is locked by
// the force-push (surface) + clean (no-surface) assertions in test-server.mjs.
const ACTIONABLE_VALIDATION_HEADS = Object.freeze([
  "STOP — Action requires acknowledgement.", // halt-and-report
  "ADVISORY — Acknowledge in next message.", // advisory
  "POST-MORTEM — Recorded for next session.", // post-mortem (defensive; Stop-class)
]);
function isActionableValidation(validation) {
  return (
    typeof validation === "string" &&
    ACTIONABLE_VALIDATION_HEADS.some((h) => validation.startsWith(h))
  );
}

// #820 output-contract alignment: build the CC PreToolUse hookSpecificOutput
// contract shape the guard RE-EMITS on its MCP response `_meta`, so a downstream
// reader of the replayed verdict sees the SAME decision fields CC's own hooks emit
// — `permissionDecision` + `permissionDecisionReason` for a deny (structural block),
// `additionalContext` for an advisory/surface (forwarded halt-and-report) — stamped
// with COC_RUNTIME so the verdict is attributable to the Codex enforcement lane.
// This is PURELY ADDITIVE: the guard's isError/content decision and the existing
// `_meta` fields are untouched, so the fail-closed policy behavior is preserved.
// Per `hook-output-discipline.md` MUST-2 the SURFACE path stamps
// permissionDecision:"allow" (a lexical/advisory match forwards the tool and rides
// `additionalContext`, NEVER carrying a block); only a structural deny (hook exit 2 /
// continue:false / permissionDecision:"deny") stamps permissionDecision:"deny".
function ccHookSpecificOutput({ decision, reason, context }) {
  const out = {
    hookEventName: "PreToolUse",
    permissionDecision: decision,
    coc_runtime: COC_RUNTIME,
  };
  if (reason != null) out.permissionDecisionReason = reason;
  if (context != null) out.additionalContext = context;
  return out;
}

function translateDeny({ hookFile, hookStdout, hookStderr }) {
  const { validation, continueFlag } = extractHookValidation(hookStdout);
  const text =
    validation ||
    `codex-mcp-guard: hook ${hookFile} blocked the tool invocation` +
      (hookStderr ? `\n\nstderr: ${hookStderr.slice(0, 400)}` : "");
  return {
    isError: true,
    content: [{ type: "text", text }],
    _meta: {
      hook: hookFile,
      continue: continueFlag,
      // #820: re-emit the CC deny contract (permissionDecision + reason) so a
      // consumer of the guard's verdict reconstructs the same decision CC's hook
      // emitted, instead of re-parsing the human-readable text.
      hookSpecificOutput: ccHookSpecificOutput({
        decision: "deny",
        reason: text,
      }),
    },
  };
}

// Build the deny response for a FAIL-CLOSED block (#411): the guard could not
// EVALUATE a policy (the hook crashed / hung / its source file is missing), so
// the call is denied rather than silently forwarded. The agent-facing text names
// the un-evaluable hook + WHY the call was blocked so the operator can fix the
// hook (the deny is on the guard's inability to evaluate, NOT on the tool input).
function failClosedDeny({ hookFile, verdict, stderr }) {
  const why = {
    timeout: "timed out (hung)",
    error: "crashed or failed to spawn",
    missing: "is missing (no policy source file for a gated tool)",
    crash:
      "launched then crashed (uncaught exception / load error) before emitting a decision",
  };
  const text =
    `codex-mcp-guard: BLOCKED (fail-closed) — the enforcement hook ${hookFile} ` +
    `${why[verdict] || "could not be evaluated"}, so the guard cannot verify this ` +
    `tool call against policy. On a governance/compliance bus a guard that cannot ` +
    `evaluate denies rather than forwards (#411). Fix or restore the hook, then retry.` +
    (stderr ? `\n\nstderr: ${String(stderr).slice(0, 400)}` : "");
  return {
    isError: true,
    content: [{ type: "text", text }],
    _meta: {
      hook: hookFile,
      continue: false,
      fail_closed: true,
      verdict,
      // #820: a fail-closed block is still a DENY in the CC contract — the guard
      // could not EVALUATE policy so it denies (never fails open). Re-emit the deny
      // decision + reason alongside the fail_closed marker so a consumer sees both
      // the CC-contract verdict AND that it came from the guard's inability to
      // evaluate (not from the tool input).
      hookSpecificOutput: ccHookSpecificOutput({
        decision: "deny",
        reason: text,
      }),
    },
  };
}

// Project a Codex tool's input into the LIST of CC tool_input shapes the
// replayed CC hooks consume — one per edit target, so a multi-file apply_patch
// is gated PER TARGET. The earlier first-target-only projection bypassed every
// TARGET-SPECIFIC gate branch on a non-first target (R1 security MED-1 +
// reviewer LOW-1): posture-gate's `.claude/learning/` write fence
// (posture-gate.js R6-C-02) and signing-mutation-guard's sibling-worktree
// contention block both key on the concrete `file_path`, so a benign first
// target + a sensitive/contended second target slipped through. Evaluating
// every target (first-deny short-circuits) closes that gap.
//
// FIELDED projection (NOT a raw spread): only the fields the gates actually
// consume reach the hook subprocess — `file_path` for apply_patch, `command`
// for shell/unified_exec. This mirrors synthesizeCaptureInput's secrets fence
// (R1 security MED-2): raw V4A patch CONTENT (which may carry secret values)
// and any unmodelled raw field never flow to a hook's stdin / violations.jsonl.
// No parseable target → a single `{}` input (gate classifies {kind:"none"} →
// passthrough, the safe degenerate direction). Reuses parseApplyPatchTargets
// (the capture path's V4A parser) so the two paths cannot drift.
function synthesizePolicyInputs(tool, input) {
  if (tool === "apply_patch") {
    const targets = parseApplyPatchTargets(input);
    if (targets.length === 0) return [{}];
    return targets.map((file_path) => ({ file_path }));
  }
  // shell / unified_exec → the Bash classifiers read `.command` only.
  const command =
    input && typeof input === "object" && typeof input.command === "string"
      ? input.command
      : "";
  return [{ command }];
}

// ---------------------------------------------------------------------------
// Policy execution — the load-bearing function
// ---------------------------------------------------------------------------
// Runs every policy registered for `tool` against `input`. Returns
// either { allow: true } or { allow: false, mcpResponse: <isError> }.
// First deny short-circuits remaining policies (the same as CC's hook
// chain semantics — first hook to exit 2 blocks the tool call).
function evaluatePolicies({ tool, input, session_id, cwd }) {
  const list = POLICIES[tool] || [];
  if (list.length === 0) {
    // No policies for this tool — but POLICIES_POPULATED gate above
    // guarantees at least one wrapped tool has policies. Empty per-
    // tool array means "no enforcement on this specific tool"; the
    // call forwards (allow). This matches CC behavior where a tool
    // matcher with zero hooks does not block the call.
    return { allow: true, warnings: [], decisions: [] };
  }
  // Present the CC-native tool name + tool_input shape to the CC hooks so
  // their tool-name classification fires (FF-AC6-1 walk finding — see
  // CODEX_TO_CC_TOOL). ccToolInputs is a LIST (one per apply_patch edit target)
  // so every TARGET-SPECIFIC gate branch sees every target (R1 security MED-1).
  const ccToolName = CODEX_TO_CC_TOOL[tool] || tool;
  const allInputs = synthesizePolicyInputs(tool, input);
  const decisions = [];
  // halt-and-report validations from "surface"-verdict hooks (exit 0 +
  // validation). The tool is forwarded (allow) BUT each message is surfaced
  // to the Codex agent so it receives the same advisory a CC agent would —
  // closing the cross-cli-parity.md MUST-1 gap (#442).
  const warnings = [];
  // Cap the per-target fan-out (R2 security LOW-R2-2). Overflow targets are
  // NOT silently allowed: surface a halt-and-report advisory + log a breadcrumb.
  let ccToolInputs = allInputs;
  if (allInputs.length > MAX_GATE_TARGETS) {
    ccToolInputs = allInputs.slice(0, MAX_GATE_TARGETS);
    warnings.push({
      source_file: "codex-mcp-guard",
      validation: `apply_patch touches ${allInputs.length} targets; only the first ${MAX_GATE_TARGETS} were gated per-target — review the remaining ${allInputs.length - MAX_GATE_TARGETS} manually.`,
    });
    logViolation({
      kind: "codex_mcp_guard_target_cap",
      tool,
      target_count: allInputs.length,
      cap: MAX_GATE_TARGETS,
    });
  }
  for (const policy of list) {
    // Run each policy against EVERY projected target; first-deny across all
    // (policy, target) pairs short-circuits the whole chain.
    for (const ccToolInput of ccToolInputs) {
      const payload = {
        hook_event_name: "PreToolUse",
        tool_name: ccToolName,
        tool_input: ccToolInput,
        session_id: session_id || null,
        cwd: cwd || process.cwd(),
      };
      const result = invokeHook({ hookFile: policy.source_file, payload });
      decisions.push({ source_file: policy.source_file, ...result });
      if (result.verdict === "deny") {
        const mcpResponse = translateDeny({
          hookFile: policy.source_file,
          hookStdout: result.stdout,
          hookStderr: result.stderr,
        });
        logViolation({
          kind: "codex_mcp_guard_deny",
          tool,
          source_file: policy.source_file,
          cwd: payload.cwd,
          // Which projected target tripped the gate — the durable audit row
          // is otherwise lossy on a multi-target patch (R2 security LOW-R2-3).
          // A shell `command` may carry secret values, so slice it to 120 chars
          // for parity with validate-bash-command.js's truncation discipline
          // (R3 security LOW-R3-1); a file_path is not secret-bearing.
          target:
            ccToolInput.file_path ||
            (typeof ccToolInput.command === "string"
              ? ccToolInput.command.slice(0, 120)
              : null),
        });
        return { allow: false, mcpResponse, decisions };
      }
      if (result.verdict === "surface") {
        // Halt-and-report: forward the tool BUT capture the validation so the
        // MCP handler surfaces it. NOT a deny — the loop continues (a later
        // policy/target may still deny). Logged as a breadcrumb (a forwarded
        // halt-and-report is a non-trivial decision the agent must act on).
        warnings.push({
          source_file: policy.source_file,
          validation: result.validation,
        });
        logViolation({
          kind: "codex_mcp_guard_surface",
          tool,
          source_file: policy.source_file,
          cwd: payload.cwd,
        });
        continue;
      }
      if (result.verdict === "warn") {
        // The hook RAN and returned a clean non-2, non-zero exit — an advisory
        // deviation, NOT a guard failure. The hook successfully evaluated the
        // policy and chose not to deny, so the call proceeds (advisory-forward).
        // This is the only non-deny verdict that does NOT fail closed below: a
        // ran-and-warned hook is distinct from a hook that could not be evaluated.
        logViolation({
          kind: "codex_mcp_guard_warn",
          tool,
          source_file: policy.source_file,
          exit_code: result.exitCode,
        });
        continue;
      }
      // FAIL-CLOSED (#411 compliance-bus posture). A verdict of `timeout` (hook
      // hung), `error` (hook failed to spawn), `missing` (the policy source file is
      // absent for a tool the POLICIES_POPULATED gate says HAS policies), or `crash`
      // (F-CGUARD-EXIT1: the hook node LAUNCHED then threw / failed to load, exiting
      // non-zero with NO parseable stdout decision) means the guard COULD NOT EVALUATE
      // the policy — it has no basis to allow. On a governance/compliance bus a guard
      // that cannot evaluate MUST DENY, never silently forward (the #411 "fail-open on
      // hook crash" gap: a crashed enforcement hook silently disabling Codex policy
      // enforcement defeats the "the model cannot bypass" guarantee). This is DISTINCT
      // from `cc-artifacts.md` Rule 7's session-hook fail-open: that governs a
      // session-CONTINUATION hook (a buggy hook must not wedge the whole session,
      // so its instructAndWait fallback emits {continue:true}); THIS is a security
      // policy-ENFORCEMENT guard whose whole purpose is to gate the call. The `crash`
      // discriminator (hasParseableHookDecision) is what lets that same Rule-7
      // {continue:true}-then-exit-1 advisory be HONORED (verdict `warn`) while a
      // decision-less load-crash fails closed here. First un-evaluable hook
      // short-circuits the chain, same as a deny.
      if (
        result.verdict === "timeout" ||
        result.verdict === "error" ||
        result.verdict === "missing" ||
        result.verdict === "crash"
      ) {
        logViolation({
          kind: "codex_mcp_guard_failclosed_" + result.verdict,
          tool,
          source_file: policy.source_file,
          exit_code: result.exitCode,
          timeout_ms:
            result.verdict === "timeout" ? SUBPROCESS_TIMEOUT_MS : undefined,
        });
        return {
          allow: false,
          mcpResponse: failClosedDeny({
            hookFile: policy.source_file,
            verdict: result.verdict,
            stderr: result.stderr,
          }),
          decisions,
        };
      }
      // Defense-in-depth (#411 fail-closed completeness). The ONLY verdict that
      // reaches here is "allow" — deny / surface / warn / timeout / error /
      // missing each returned or continued above. A FUTURE, unmodeled verdict
      // string MUST NOT silently fall through to the allow at the function tail:
      // an unrecognized verdict means the guard cannot reason about the hook's
      // intent, so it fails closed (same posture as the un-evaluable trio).
      if (result.verdict !== "allow") {
        logViolation({
          kind: "codex_mcp_guard_failclosed_unmodeled",
          tool,
          source_file: policy.source_file,
          verdict: result.verdict,
        });
        return {
          allow: false,
          mcpResponse: failClosedDeny({
            hookFile: policy.source_file,
            verdict: result.verdict || "unknown",
            stderr: result.stderr,
          }),
          decisions,
        };
      }
    }
  }
  return { allow: true, warnings, decisions };
}

// ---------------------------------------------------------------------------
// Allow-path MCP response builder — plain permit OR forward+warn
// ---------------------------------------------------------------------------
// For an ALLOWED tool call, builds the MCP response. When the call carried
// halt-and-report warnings (exit-0 hooks with a validation message), the
// response surfaces them in content[].text — mirroring CC's continue:true +
// surfaced-message semantics so the Codex agent sees the same advisory a CC
// agent would. isError stays false (the tool IS forwarded). Plain allow (no
// warnings) returns the bare "permit" the guard has always emitted.
function buildAllowResponse(result) {
  if (result && Array.isArray(result.warnings) && result.warnings.length > 0) {
    const warnText = result.warnings
      .map((w) => w.validation)
      .filter(Boolean)
      .join("\n\n");
    return {
      content: [
        {
          type: "text",
          text:
            "permit\n\n⚠ halt-and-report (tool forwarded — surface to user):\n\n" +
            warnText,
        },
      ],
      _meta: {
        warnings: result.warnings,
        // #820: a forwarded halt-and-report is an ALLOW decision carrying an
        // advisory — re-emit the CC contract with permissionDecision:"allow" +
        // additionalContext (NEVER a block; per hook-output-discipline.md MUST-2 a
        // lexical/advisory match must not carry deny). isError stays false: the
        // tool IS forwarded, exactly as CC's continue:true + surfaced-message.
        hookSpecificOutput: ccHookSpecificOutput({
          decision: "allow",
          context: warnText,
        }),
      },
    };
  }
  return { content: [{ type: "text", text: "permit" }] };
}

// ---------------------------------------------------------------------------
// Provenance capture side-effect — the load-bearing #440 function
// ---------------------------------------------------------------------------
// Extract V4A target file path(s) from an apply_patch tool input. The patch text
// may arrive under any key (the exact Codex MCP arg shape is unverified from loom;
// see journal/0218 residual), so scan all string values (bounded depth) for the
// documented V4A markers. Returns [] when no patch text / no markers are found
// (→ caller degrades to Action, the write-tool default — never a fake event).
function parseApplyPatchTargets(input) {
  const paths = [];
  const seen = new Set();
  const scanString = (s) => {
    for (const line of s.split("\n")) {
      const m = line.match(V4A_FILE_RE) || line.match(V4A_MOVE_RE);
      if (m && m[1]) {
        const p = m[1].trim();
        if (p && !seen.has(p)) {
          seen.add(p);
          paths.push(p);
        }
      }
    }
  };
  const walk = (node, depth) => {
    if (node == null || depth > 4) return;
    if (typeof node === "string") return scanString(node);
    if (Array.isArray(node)) {
      for (const v of node) walk(v, depth + 1);
      return;
    }
    if (typeof node === "object") {
      for (const v of Object.values(node)) walk(v, depth + 1);
    }
  };
  walk(input, 0);
  return paths;
}

// Build the CC-shaped tool_input the capture hook's classify() consumes. For
// apply_patch, extract the V4A target and PREFER a journal-DECISION path so
// classify() records a Decision (else Action). No path → {} (classify → Action,
// the write-tool default). Non-apply_patch tools are not captured here.
function synthesizeCaptureInput(tool, input) {
  // Only apply_patch is captured via the guard (CAPTURE_TOOLS). For any other
  // tool return {} — NEVER the raw input — so that if CAPTURE_TOOLS ever widens
  // to a command-bearing tool, a raw command (which may carry secret VALUES in
  // its argv) cannot flow to the permanent ledger through this path. The secrets
  // fence stays airtight by construction here, not only via runProvenanceCapture's
  // scope gate. A future capturer for another tool MUST extend this function with
  // a fielded projection — and the self-referential-codify gate fires on that edit
  // (security R1 LOW defense-in-depth, journal/0219).
  if (tool !== "apply_patch") return {};
  const targets = parseApplyPatchTargets(input);
  if (targets.length === 0) return {};
  const re = journalDecisionRe();
  const decisionTarget = re ? targets.find((p) => re.test(p)) : null;
  return { file_path: decisionTarget || targets[0] };
}

// Non-blocking governance capture: invoke the capture hook as a side-effect on a
// wrapped tool. NEVER denies the tool call (the hook always exits 0); a non-zero/
// timeout verdict is a capture degradation logged to violations.jsonl, never a
// block. The MCP handler runs this BEFORE evaluatePolicies so INTENT is captured
// even when a sibling policy later denies (journal/0216 intent-vs-execution).
function runProvenanceCapture({ tool, input, session_id, cwd }) {
  if (!CAPTURE_TOOLS.includes(tool)) {
    return { captured: false, reason: "tool-not-in-capture-scope" };
  }
  try {
    const tool_input = synthesizeCaptureInput(tool, input);
    const payload = {
      hook_event_name: "PreToolUse",
      tool_name: tool,
      tool_input,
      session_id: session_id || null,
      cwd: cwd || process.cwd(),
    };
    const r = invokeHook({ hookFile: CAPTURE_HOOK, payload });
    if (r.verdict !== "allow") {
      // The capture hook exits 0 on every path; a non-allow verdict means the
      // hook is missing/buggy/slow — log the degradation, never block the call.
      logViolation({
        kind: "codex_mcp_guard_capture_" + r.verdict,
        tool,
        source_file: CAPTURE_HOOK,
        exit_code: r.exitCode,
      });
    }
    return { captured: r.verdict === "allow", verdict: r.verdict, tool_input };
  } catch (e) {
    logViolation({
      kind: "codex_mcp_guard_capture_error",
      tool,
      source_file: CAPTURE_HOOK,
      error: String((e && e.message) || e),
    });
    return { captured: false, reason: "exception" };
  }
}

// ---------------------------------------------------------------------------
// Self-check — design per task spec acceptance criteria
// ---------------------------------------------------------------------------
function selfCheck() {
  const lines = [];
  lines.push(`POLICIES_POPULATED=${POLICIES_POPULATED}`);
  lines.push(`POLICIES_SOURCE=${POLICIES_SOURCE || "(none)"}`);
  for (const t of WRAPPED_TOOLS) {
    const list = POLICIES[t] || [];
    lines.push(
      `tool=${t} entries=${list.length} files=[${list.map((e) => e.source_file).join(",")}]`,
    );
  }
  lines.push(
    `HOOKS_DIR=${HOOKS_DIR} hooks_dir_exists=${fs.existsSync(HOOKS_DIR)}`,
  );
  lines.push(`SUBPROCESS_TIMEOUT_MS=${SUBPROCESS_TIMEOUT_MS}`);
  process.stdout.write(lines.join("\n") + "\n");
  process.exit(POLICIES_POPULATED ? 0 : 2);
}

// ---------------------------------------------------------------------------
// Smoke check — run a synthetic tool call through evaluatePolicies and
// print the verdict. Used by the test harness; exposed via CLI flag.
// Usage: node server.js --smoke <tool> <json-tool-input>
// ---------------------------------------------------------------------------
function smokeCheck(tool, toolInputJson) {
  if (!WRAPPED_TOOLS.includes(tool)) {
    process.stderr.write(
      `--smoke: tool must be one of ${WRAPPED_TOOLS.join(",")}; got '${tool}'\n`,
    );
    process.exit(2);
  }
  let input;
  try {
    input = JSON.parse(toolInputJson);
  } catch (e) {
    process.stderr.write(`--smoke: invalid JSON tool_input: ${e.message}\n`);
    process.exit(2);
  }
  const result = evaluatePolicies({ tool, input, cwd: process.cwd() });
  process.stdout.write(JSON.stringify(result, null, 2) + "\n");
  process.exit(result.allow ? 0 : 1);
}

// ---------------------------------------------------------------------------
// Structural feature-flag gate — prevents fail-open default
// ---------------------------------------------------------------------------
// Zero-tolerance Rule 2 requires no stubs in production code paths. The
// POLICIES table is populated by /sync from extract-policies.mjs at
// emit time. If POLICIES_POPULATED is false here, the policies.json
// either does not exist or has empty per-tool arrays — running the
// server in that state would fail-open on every tool invocation,
// which is worse than no guardrail at all. Refuse to start.
function refuseUnpopulated() {
  process.stderr.write(
    [
      "codex-mcp-guard: refusing to start with unpopulated POLICIES table.",
      "",
      "policies.json is missing or has no per-tool entries. Running the",
      "server in this state would fail-open on every tool invocation,",
      "which is worse than no guardrail at all (zero-tolerance Rule 2).",
      "",
      "To populate:",
      "  1. Ensure .claude/hooks/*.js contains the production hook policies.",
      "  2. node .codex-mcp-guard/extract-policies.mjs <hook-dir> \\",
      "       --write-policies .codex-mcp-guard/policies.json",
      "  3. Re-run this server.",
      "",
      "See .codex-mcp-guard/README.md § Authoring.",
      "",
    ].join("\n"),
  );
  process.exit(2);
}

// ---------------------------------------------------------------------------
// MCP server entry — lazy-loads @modelcontextprotocol/sdk only when
// actually serving stdio. Keeps the module importable / testable in
// repos where the SDK is not installed (CI on the loom side).
// ---------------------------------------------------------------------------
async function serveStdio() {
  // Lazy-loaded so the test harness + self-check can run without the
  // MCP SDK npm dependency installed in the host repo. The USE
  // template's package.json declares the dep at install time.
  let McpServer, StdioServerTransport, z;
  try {
    ({ McpServer } = require("@modelcontextprotocol/sdk/server/mcp.js"));
    ({
      StdioServerTransport,
    } = require("@modelcontextprotocol/sdk/server/stdio.js"));
    ({ z } = require("zod"));
  } catch (e) {
    process.stderr.write(
      `codex-mcp-guard: @modelcontextprotocol/sdk not installed (${e.message}).\n` +
        "Install via the USE template's package.json before running stdio mode.\n",
    );
    process.exit(2);
  }

  const server = new McpServer(
    { name: "codex-mcp-guard", version: "0.2.0" },
    { capabilities: { tools: {} } },
  );

  const inputShape = {
    input: z.record(z.string(), z.unknown()),
    session_id: z.string().optional(),
    cwd: z.string().optional(),
  };

  for (const tool of WRAPPED_TOOLS) {
    server.registerTool(
      tool,
      {
        description: `Guardrail wrapper for Codex ${tool} — enforces hooks/*.js parity`,
        inputSchema: inputShape,
      },
      async ({ input, session_id, cwd }) => {
        // Governance capture FIRST (non-blocking, intent-time) — runs before
        // policy evaluation so a provenance event is recorded even if a sibling
        // policy denies the tool call (loom#411 item 1 / #440; journal/0218).
        // Defense-in-depth: runProvenanceCapture is internally guarded, but the
        // capture side-effect MUST NEVER block a tool call, so the call site is
        // wrapped too — a capture throw is swallowed, policy eval proceeds
        // unchanged (cc-architect R1 LOW, journal/0219).
        try {
          runProvenanceCapture({ tool, input, session_id, cwd });
        } catch {
          /* capture is best-effort; never block the tool call */
        }
        const result = evaluatePolicies({ tool, input, session_id, cwd });
        if (!result.allow) return result.mcpResponse;
        // Allowed — plain permit, OR forward+warn when a halt-and-report hook
        // surfaced a validation message (#442 cross-CLI parity).
        return buildAllowResponse(result);
      },
    );
  }

  const transport = new StdioServerTransport();
  await server.connect(transport);
}

// ---------------------------------------------------------------------------
// CLI dispatch
// ---------------------------------------------------------------------------
if (require.main === module) {
  const args = process.argv.slice(2);
  if (args[0] === "--self-check") {
    selfCheck();
  } else if (args[0] === "--smoke") {
    if (args.length < 3) {
      process.stderr.write(
        "usage: server.js --smoke <tool> <json-tool-input>\n",
      );
      process.exit(2);
    }
    if (!POLICIES_POPULATED) refuseUnpopulated();
    smokeCheck(args[1], args[2]);
  } else {
    if (!POLICIES_POPULATED) refuseUnpopulated();
    serveStdio().catch((err) => {
      process.stderr.write(`codex-mcp-guard fatal: ${err.message}\n`);
      process.exit(1);
    });
  }
}

module.exports = {
  POLICIES,
  POLICIES_POPULATED,
  POLICIES_SOURCE,
  WRAPPED_TOOLS,
  SUBPROCESS_TIMEOUT_MS,
  evaluatePolicies,
  invokeHook,
  translateDeny,
  ccHookSpecificOutput,
  extractHookValidation,
  hasParseableHookDecision,
  isActionableValidation,
  buildAllowResponse,
  loadPolicies,
  COC_RUNTIME,
  // Provenance capture (loom#411 item 1 / #440). CAPTURE_HOOKS + CAPTURE_TOOLS
  // are the SSOT the F101-4 validator reads to verify a `@codex-mcp-guard` cell.
  CAPTURE_HOOK,
  CAPTURE_HOOKS,
  CAPTURE_TOOLS,
  runProvenanceCapture,
  parseApplyPatchTargets,
  synthesizeCaptureInput,
  synthesizePolicyInputs,
  CODEX_TO_CC_TOOL,
  MAX_GATE_TARGETS,
  HOOKS_DIR,
};
